// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: battle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleStatus int32

const (
	BattleStatus_BATTLE_STATUS_UNSPECIFIED   BattleStatus = 0
	BattleStatus_BATTLE_STATUS_FIGHTING      BattleStatus = 1
	BattleStatus_BATTLE_STATUS_BETWEEN_WAVES BattleStatus = 2
	BattleStatus_BATTLE_STATUS_RESPAWN       BattleStatus = 3
	BattleStatus_BATTLE_STATUS_STOPPED       BattleStatus = 4
)

// Enum value maps for BattleStatus.
var (
	BattleStatus_name = map[int32]string{
		0: "BATTLE_STATUS_UNSPECIFIED",
		1: "BATTLE_STATUS_FIGHTING",
		2: "BATTLE_STATUS_BETWEEN_WAVES",
		3: "BATTLE_STATUS_RESPAWN",
		4: "BATTLE_STATUS_STOPPED",
	}
	BattleStatus_value = map[string]int32{
		"BATTLE_STATUS_UNSPECIFIED":   0,
		"BATTLE_STATUS_FIGHTING":      1,
		"BATTLE_STATUS_BETWEEN_WAVES": 2,
		"BATTLE_STATUS_RESPAWN":       3,
		"BATTLE_STATUS_STOPPED":       4,
	}
)

func (x BattleStatus) Enum() *BattleStatus {
	p := new(BattleStatus)
	*p = x
	return p
}

func (x BattleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[0].Descriptor()
}

func (BattleStatus) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[0]
}

func (x BattleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleStatus.Descriptor instead.
func (BattleStatus) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

type BattleLogType int32

const (
	BattleLogType_BATTLE_LOG_TYPE_UNSPECIFIED        BattleLogType = 0
	BattleLogType_BATTLE_LOG_TYPE_PLAYER_ATTACK      BattleLogType = 1
	BattleLogType_BATTLE_LOG_TYPE_ENEMY_ATTACK       BattleLogType = 2
	BattleLogType_BATTLE_LOG_TYPE_ENEMY_DIED         BattleLogType = 3
	BattleLogType_BATTLE_LOG_TYPE_PLAYER_DOWNED      BattleLogType = 4
	BattleLogType_BATTLE_LOG_TYPE_PLAYER_RESPAWN     BattleLogType = 5
	BattleLogType_BATTLE_LOG_TYPE_WAVE_SPAWNED       BattleLogType = 6
	BattleLogType_BATTLE_LOG_TYPE_WAVE_CLEARED       BattleLogType = 7
	BattleLogType_BATTLE_LOG_TYPE_ALL_PLAYERS_DOWNED BattleLogType = 8
	BattleLogType_BATTLE_LOG_TYPE_STOPPED            BattleLogType = 9
)

// Enum value maps for BattleLogType.
var (
	BattleLogType_name = map[int32]string{
		0: "BATTLE_LOG_TYPE_UNSPECIFIED",
		1: "BATTLE_LOG_TYPE_PLAYER_ATTACK",
		2: "BATTLE_LOG_TYPE_ENEMY_ATTACK",
		3: "BATTLE_LOG_TYPE_ENEMY_DIED",
		4: "BATTLE_LOG_TYPE_PLAYER_DOWNED",
		5: "BATTLE_LOG_TYPE_PLAYER_RESPAWN",
		6: "BATTLE_LOG_TYPE_WAVE_SPAWNED",
		7: "BATTLE_LOG_TYPE_WAVE_CLEARED",
		8: "BATTLE_LOG_TYPE_ALL_PLAYERS_DOWNED",
		9: "BATTLE_LOG_TYPE_STOPPED",
	}
	BattleLogType_value = map[string]int32{
		"BATTLE_LOG_TYPE_UNSPECIFIED":        0,
		"BATTLE_LOG_TYPE_PLAYER_ATTACK":      1,
		"BATTLE_LOG_TYPE_ENEMY_ATTACK":       2,
		"BATTLE_LOG_TYPE_ENEMY_DIED":         3,
		"BATTLE_LOG_TYPE_PLAYER_DOWNED":      4,
		"BATTLE_LOG_TYPE_PLAYER_RESPAWN":     5,
		"BATTLE_LOG_TYPE_WAVE_SPAWNED":       6,
		"BATTLE_LOG_TYPE_WAVE_CLEARED":       7,
		"BATTLE_LOG_TYPE_ALL_PLAYERS_DOWNED": 8,
		"BATTLE_LOG_TYPE_STOPPED":            9,
	}
)

func (x BattleLogType) Enum() *BattleLogType {
	p := new(BattleLogType)
	*p = x
	return p
}

func (x BattleLogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleLogType) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[1].Descriptor()
}

func (BattleLogType) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[1]
}

func (x BattleLogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleLogType.Descriptor instead.
func (BattleLogType) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

type BattleEntityState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EntityId               int64                  `protobuf:"zigzag64,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Alive                  bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Hp                     float64                `protobuf:"fixed64,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp                  float64                `protobuf:"fixed64,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Mp                     float64                `protobuf:"fixed64,5,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxMp                  float64                `protobuf:"fixed64,6,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Sp                     float64                `protobuf:"fixed64,7,opt,name=sp,proto3" json:"sp,omitempty"`
	MaxSp                  float64                `protobuf:"fixed64,8,opt,name=max_sp,json=maxSp,proto3" json:"max_sp,omitempty"`
	NextReadyIn            float64                `protobuf:"fixed64,9,opt,name=next_ready_in,json=nextReadyIn,proto3" json:"next_ready_in,omitempty"`
	ActionCooldownSeconds  float64                `protobuf:"fixed64,10,opt,name=action_cooldown_seconds,json=actionCooldownSeconds,proto3" json:"action_cooldown_seconds,omitempty"`
	ActionCooldownProgress float64                `protobuf:"fixed64,11,opt,name=action_cooldown_progress,json=actionCooldownProgress,proto3" json:"action_cooldown_progress,omitempty"`
	LastSkillId            int64                  `protobuf:"zigzag64,12,opt,name=last_skill_id,json=lastSkillId,proto3" json:"last_skill_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BattleEntityState) Reset() {
	*x = BattleEntityState{}
	mi := &file_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEntityState) ProtoMessage() {}

func (x *BattleEntityState) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEntityState.ProtoReflect.Descriptor instead.
func (*BattleEntityState) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

func (x *BattleEntityState) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *BattleEntityState) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *BattleEntityState) GetHp() float64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *BattleEntityState) GetMaxHp() float64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *BattleEntityState) GetMp() float64 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *BattleEntityState) GetMaxMp() float64 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *BattleEntityState) GetSp() float64 {
	if x != nil {
		return x.Sp
	}
	return 0
}

func (x *BattleEntityState) GetMaxSp() float64 {
	if x != nil {
		return x.MaxSp
	}
	return 0
}

func (x *BattleEntityState) GetNextReadyIn() float64 {
	if x != nil {
		return x.NextReadyIn
	}
	return 0
}

func (x *BattleEntityState) GetActionCooldownSeconds() float64 {
	if x != nil {
		return x.ActionCooldownSeconds
	}
	return 0
}

func (x *BattleEntityState) GetActionCooldownProgress() float64 {
	if x != nil {
		return x.ActionCooldownProgress
	}
	return 0
}

func (x *BattleEntityState) GetLastSkillId() int64 {
	if x != nil {
		return x.LastSkillId
	}
	return 0
}

type BattleLogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             BattleLogType          `protobuf:"varint,1,opt,name=type,proto3,enum=mli.v1.BattleLogType" json:"type,omitempty"`
	AttackerEntityId int64                  `protobuf:"zigzag64,2,opt,name=attacker_entity_id,json=attackerEntityId,proto3" json:"attacker_entity_id,omitempty"`
	DefenderEntityId int64                  `protobuf:"zigzag64,3,opt,name=defender_entity_id,json=defenderEntityId,proto3" json:"defender_entity_id,omitempty"`
	SkillId          int64                  `protobuf:"zigzag64,4,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Damage           float64                `protobuf:"fixed64,5,opt,name=damage,proto3" json:"damage,omitempty"`
	RawDamage        float64                `protobuf:"fixed64,6,opt,name=raw_damage,json=rawDamage,proto3" json:"raw_damage,omitempty"`
	Evaded           bool                   `protobuf:"varint,7,opt,name=evaded,proto3" json:"evaded,omitempty"`
	Blocked          bool                   `protobuf:"varint,8,opt,name=blocked,proto3" json:"blocked,omitempty"`
	BlockedReduction float64                `protobuf:"fixed64,9,opt,name=blocked_reduction,json=blockedReduction,proto3" json:"blocked_reduction,omitempty"`
	DefenderHp       float64                `protobuf:"fixed64,10,opt,name=defender_hp,json=defenderHp,proto3" json:"defender_hp,omitempty"`
	WaveNumber       int32                  `protobuf:"varint,11,opt,name=wave_number,json=waveNumber,proto3" json:"wave_number,omitempty"`
	NextWaveIn       float64                `protobuf:"fixed64,12,opt,name=next_wave_in,json=nextWaveIn,proto3" json:"next_wave_in,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BattleLogEntry) Reset() {
	*x = BattleLogEntry{}
	mi := &file_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleLogEntry) ProtoMessage() {}

func (x *BattleLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleLogEntry.ProtoReflect.Descriptor instead.
func (*BattleLogEntry) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

func (x *BattleLogEntry) GetType() BattleLogType {
	if x != nil {
		return x.Type
	}
	return BattleLogType_BATTLE_LOG_TYPE_UNSPECIFIED
}

func (x *BattleLogEntry) GetAttackerEntityId() int64 {
	if x != nil {
		return x.AttackerEntityId
	}
	return 0
}

func (x *BattleLogEntry) GetDefenderEntityId() int64 {
	if x != nil {
		return x.DefenderEntityId
	}
	return 0
}

func (x *BattleLogEntry) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *BattleLogEntry) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *BattleLogEntry) GetRawDamage() float64 {
	if x != nil {
		return x.RawDamage
	}
	return 0
}

func (x *BattleLogEntry) GetEvaded() bool {
	if x != nil {
		return x.Evaded
	}
	return false
}

func (x *BattleLogEntry) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *BattleLogEntry) GetBlockedReduction() float64 {
	if x != nil {
		return x.BlockedReduction
	}
	return 0
}

func (x *BattleLogEntry) GetDefenderHp() float64 {
	if x != nil {
		return x.DefenderHp
	}
	return 0
}

func (x *BattleLogEntry) GetWaveNumber() int32 {
	if x != nil {
		return x.WaveNumber
	}
	return 0
}

func (x *BattleLogEntry) GetNextWaveIn() float64 {
	if x != nil {
		return x.NextWaveIn
	}
	return 0
}

// Layer 1: full snapshot (first connect, reconnect, heartbeat)
type BattleSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Status        BattleStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=mli.v1.BattleStatus" json:"status,omitempty"`
	Time          float64                `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`
	WaveNumber    int32                  `protobuf:"varint,4,opt,name=wave_number,json=waveNumber,proto3" json:"wave_number,omitempty"`
	NextStepIn    float64                `protobuf:"fixed64,5,opt,name=next_step_in,json=nextStepIn,proto3" json:"next_step_in,omitempty"`
	Players       []*BattleEntityState   `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	Enemies       []*BattleEntityState   `protobuf:"bytes,7,rep,name=enemies,proto3" json:"enemies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleSnapshot) Reset() {
	*x = BattleSnapshot{}
	mi := &file_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleSnapshot) ProtoMessage() {}

func (x *BattleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleSnapshot.ProtoReflect.Descriptor instead.
func (*BattleSnapshot) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{2}
}

func (x *BattleSnapshot) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleSnapshot) GetStatus() BattleStatus {
	if x != nil {
		return x.Status
	}
	return BattleStatus_BATTLE_STATUS_UNSPECIFIED
}

func (x *BattleSnapshot) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BattleSnapshot) GetWaveNumber() int32 {
	if x != nil {
		return x.WaveNumber
	}
	return 0
}

func (x *BattleSnapshot) GetNextStepIn() float64 {
	if x != nil {
		return x.NextStepIn
	}
	return 0
}

func (x *BattleSnapshot) GetPlayers() []*BattleEntityState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *BattleSnapshot) GetEnemies() []*BattleEntityState {
	if x != nil {
		return x.Enemies
	}
	return nil
}

// Layer 2: event batch (pushed only when combat events occur)
type BattleEventBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Time             float64                `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	Logs             []*BattleLogEntry      `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	AffectedEntities []*BattleEntityState   `protobuf:"bytes,3,rep,name=affected_entities,json=affectedEntities,proto3" json:"affected_entities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BattleEventBatch) Reset() {
	*x = BattleEventBatch{}
	mi := &file_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEventBatch) ProtoMessage() {}

func (x *BattleEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEventBatch.ProtoReflect.Descriptor instead.
func (*BattleEventBatch) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{3}
}

func (x *BattleEventBatch) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BattleEventBatch) GetLogs() []*BattleLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *BattleEventBatch) GetAffectedEntities() []*BattleEntityState {
	if x != nil {
		return x.AffectedEntities
	}
	return nil
}

type BattleStartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStartReq) Reset() {
	*x = BattleStartReq{}
	mi := &file_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStartReq) ProtoMessage() {}

func (x *BattleStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStartReq.ProtoReflect.Descriptor instead.
func (*BattleStartReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{4}
}

func (x *BattleStartReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type BattleStartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *BattleSnapshot        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStartResp) Reset() {
	*x = BattleStartResp{}
	mi := &file_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStartResp) ProtoMessage() {}

func (x *BattleStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStartResp.ProtoReflect.Descriptor instead.
func (*BattleStartResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{5}
}

func (x *BattleStartResp) GetSnapshot() *BattleSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type BattleStopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStopReq) Reset() {
	*x = BattleStopReq{}
	mi := &file_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStopReq) ProtoMessage() {}

func (x *BattleStopReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStopReq.ProtoReflect.Descriptor instead.
func (*BattleStopReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{6}
}

type BattleStopResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *BattleSnapshot        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStopResp) Reset() {
	*x = BattleStopResp{}
	mi := &file_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStopResp) ProtoMessage() {}

func (x *BattleStopResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStopResp.ProtoReflect.Descriptor instead.
func (*BattleStopResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7}
}

func (x *BattleStopResp) GetSnapshot() *BattleSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type BattleStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStateReq) Reset() {
	*x = BattleStateReq{}
	mi := &file_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStateReq) ProtoMessage() {}

func (x *BattleStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStateReq.ProtoReflect.Descriptor instead.
func (*BattleStateReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{8}
}

type BattleStateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *BattleSnapshot        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStateResp) Reset() {
	*x = BattleStateResp{}
	mi := &file_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStateResp) ProtoMessage() {}

func (x *BattleStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStateResp.ProtoReflect.Descriptor instead.
func (*BattleStateResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{9}
}

func (x *BattleStateResp) GetSnapshot() *BattleSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_battle_proto protoreflect.FileDescriptor

const file_battle_proto_rawDesc = "" +
	"\n" +
	"\fbattle.proto\x12\x06mli.v1\"\xf5\x02\n" +
	"\x11BattleEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x12R\bentityId\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x01R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x01R\x05maxHp\x12\x0e\n" +
	"\x02mp\x18\x05 \x01(\x01R\x02mp\x12\x15\n" +
	"\x06max_mp\x18\x06 \x01(\x01R\x05maxMp\x12\x0e\n" +
	"\x02sp\x18\a \x01(\x01R\x02sp\x12\x15\n" +
	"\x06max_sp\x18\b \x01(\x01R\x05maxSp\x12\"\n" +
	"\rnext_ready_in\x18\t \x01(\x01R\vnextReadyIn\x126\n" +
	"\x17action_cooldown_seconds\x18\n" +
	" \x01(\x01R\x15actionCooldownSeconds\x128\n" +
	"\x18action_cooldown_progress\x18\v \x01(\x01R\x16actionCooldownProgress\x12\"\n" +
	"\rlast_skill_id\x18\f \x01(\x12R\vlastSkillId\"\xac\x03\n" +
	"\x0eBattleLogEntry\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.mli.v1.BattleLogTypeR\x04type\x12,\n" +
	"\x12attacker_entity_id\x18\x02 \x01(\x12R\x10attackerEntityId\x12,\n" +
	"\x12defender_entity_id\x18\x03 \x01(\x12R\x10defenderEntityId\x12\x19\n" +
	"\bskill_id\x18\x04 \x01(\x12R\askillId\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x01R\x06damage\x12\x1d\n" +
	"\n" +
	"raw_damage\x18\x06 \x01(\x01R\trawDamage\x12\x16\n" +
	"\x06evaded\x18\a \x01(\bR\x06evaded\x12\x18\n" +
	"\ablocked\x18\b \x01(\bR\ablocked\x12+\n" +
	"\x11blocked_reduction\x18\t \x01(\x01R\x10blockedReduction\x12\x1f\n" +
	"\vdefender_hp\x18\n" +
	" \x01(\x01R\n" +
	"defenderHp\x12\x1f\n" +
	"\vwave_number\x18\v \x01(\x05R\n" +
	"waveNumber\x12 \n" +
	"\fnext_wave_in\x18\f \x01(\x01R\n" +
	"nextWaveIn\"\x9c\x02\n" +
	"\x0eBattleSnapshot\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.mli.v1.BattleStatusR\x06status\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x01R\x04time\x12\x1f\n" +
	"\vwave_number\x18\x04 \x01(\x05R\n" +
	"waveNumber\x12 \n" +
	"\fnext_step_in\x18\x05 \x01(\x01R\n" +
	"nextStepIn\x123\n" +
	"\aplayers\x18\x06 \x03(\v2\x19.mli.v1.BattleEntityStateR\aplayers\x123\n" +
	"\aenemies\x18\a \x03(\v2\x19.mli.v1.BattleEntityStateR\aenemies\"\x9a\x01\n" +
	"\x10BattleEventBatch\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x01R\x04time\x12*\n" +
	"\x04logs\x18\x02 \x03(\v2\x16.mli.v1.BattleLogEntryR\x04logs\x12F\n" +
	"\x11affected_entities\x18\x03 \x03(\v2\x19.mli.v1.BattleEntityStateR\x10affectedEntities\"-\n" +
	"\x0eBattleStartReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"E\n" +
	"\x0fBattleStartResp\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.mli.v1.BattleSnapshotR\bsnapshot\"\x0f\n" +
	"\rBattleStopReq\"D\n" +
	"\x0eBattleStopResp\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.mli.v1.BattleSnapshotR\bsnapshot\"\x10\n" +
	"\x0eBattleStateReq\"E\n" +
	"\x0fBattleStateResp\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.mli.v1.BattleSnapshotR\bsnapshot*\xa0\x01\n" +
	"\fBattleStatus\x12\x1d\n" +
	"\x19BATTLE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BATTLE_STATUS_FIGHTING\x10\x01\x12\x1f\n" +
	"\x1bBATTLE_STATUS_BETWEEN_WAVES\x10\x02\x12\x19\n" +
	"\x15BATTLE_STATUS_RESPAWN\x10\x03\x12\x19\n" +
	"\x15BATTLE_STATUS_STOPPED\x10\x04*\xe5\x02\n" +
	"\rBattleLogType\x12\x1f\n" +
	"\x1bBATTLE_LOG_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dBATTLE_LOG_TYPE_PLAYER_ATTACK\x10\x01\x12 \n" +
	"\x1cBATTLE_LOG_TYPE_ENEMY_ATTACK\x10\x02\x12\x1e\n" +
	"\x1aBATTLE_LOG_TYPE_ENEMY_DIED\x10\x03\x12!\n" +
	"\x1dBATTLE_LOG_TYPE_PLAYER_DOWNED\x10\x04\x12\"\n" +
	"\x1eBATTLE_LOG_TYPE_PLAYER_RESPAWN\x10\x05\x12 \n" +
	"\x1cBATTLE_LOG_TYPE_WAVE_SPAWNED\x10\x06\x12 \n" +
	"\x1cBATTLE_LOG_TYPE_WAVE_CLEARED\x10\a\x12&\n" +
	"\"BATTLE_LOG_TYPE_ALL_PLAYERS_DOWNED\x10\b\x12\x1b\n" +
	"\x17BATTLE_LOG_TYPE_STOPPED\x10\tBNZLgithub.com/Milkyway-Liluo-Idle-Develop-Team/Milkyway-Liluo-Idle-2/backend/pbb\x06proto3"

var (
	file_battle_proto_rawDescOnce sync.Once
	file_battle_proto_rawDescData []byte
)

func file_battle_proto_rawDescGZIP() []byte {
	file_battle_proto_rawDescOnce.Do(func() {
		file_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)))
	})
	return file_battle_proto_rawDescData
}

var file_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_battle_proto_goTypes = []any{
	(BattleStatus)(0),         // 0: mli.v1.BattleStatus
	(BattleLogType)(0),        // 1: mli.v1.BattleLogType
	(*BattleEntityState)(nil), // 2: mli.v1.BattleEntityState
	(*BattleLogEntry)(nil),    // 3: mli.v1.BattleLogEntry
	(*BattleSnapshot)(nil),    // 4: mli.v1.BattleSnapshot
	(*BattleEventBatch)(nil),  // 5: mli.v1.BattleEventBatch
	(*BattleStartReq)(nil),    // 6: mli.v1.BattleStartReq
	(*BattleStartResp)(nil),   // 7: mli.v1.BattleStartResp
	(*BattleStopReq)(nil),     // 8: mli.v1.BattleStopReq
	(*BattleStopResp)(nil),    // 9: mli.v1.BattleStopResp
	(*BattleStateReq)(nil),    // 10: mli.v1.BattleStateReq
	(*BattleStateResp)(nil),   // 11: mli.v1.BattleStateResp
}
var file_battle_proto_depIdxs = []int32{
	1, // 0: mli.v1.BattleLogEntry.type:type_name -> mli.v1.BattleLogType
	0, // 1: mli.v1.BattleSnapshot.status:type_name -> mli.v1.BattleStatus
	2, // 2: mli.v1.BattleSnapshot.players:type_name -> mli.v1.BattleEntityState
	2, // 3: mli.v1.BattleSnapshot.enemies:type_name -> mli.v1.BattleEntityState
	3, // 4: mli.v1.BattleEventBatch.logs:type_name -> mli.v1.BattleLogEntry
	2, // 5: mli.v1.BattleEventBatch.affected_entities:type_name -> mli.v1.BattleEntityState
	4, // 6: mli.v1.BattleStartResp.snapshot:type_name -> mli.v1.BattleSnapshot
	4, // 7: mli.v1.BattleStopResp.snapshot:type_name -> mli.v1.BattleSnapshot
	4, // 8: mli.v1.BattleStateResp.snapshot:type_name -> mli.v1.BattleSnapshot
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_battle_proto_init() }
func file_battle_proto_init() {
	if File_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battle_proto_goTypes,
		DependencyIndexes: file_battle_proto_depIdxs,
		EnumInfos:         file_battle_proto_enumTypes,
		MessageInfos:      file_battle_proto_msgTypes,
	}.Build()
	File_battle_proto = out.File
	file_battle_proto_goTypes = nil
	file_battle_proto_depIdxs = nil
}
