// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/queue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueAppendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TargetCycles  int32                  `protobuf:"varint,2,opt,name=target_cycles,json=targetCycles,proto3" json:"target_cycles,omitempty"` // -1 = infinite
	QueueId       int32                  `protobuf:"varint,3,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueAppendReq) Reset() {
	*x = QueueAppendReq{}
	mi := &file_proto_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueAppendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueAppendReq) ProtoMessage() {}

func (x *QueueAppendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueAppendReq.ProtoReflect.Descriptor instead.
func (*QueueAppendReq) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueAppendReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *QueueAppendReq) GetTargetCycles() int32 {
	if x != nil {
		return x.TargetCycles
	}
	return 0
}

func (x *QueueAppendReq) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type QueueRemoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	QueueId       int32                  `protobuf:"varint,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRemoveReq) Reset() {
	*x = QueueRemoveReq{}
	mi := &file_proto_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveReq) ProtoMessage() {}

func (x *QueueRemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveReq.ProtoReflect.Descriptor instead.
func (*QueueRemoveReq) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{1}
}

func (x *QueueRemoveReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *QueueRemoveReq) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type QueueMoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPosition  int32                  `protobuf:"varint,1,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"`
	ToPosition    int32                  `protobuf:"varint,2,opt,name=to_position,json=toPosition,proto3" json:"to_position,omitempty"`
	QueueId       int32                  `protobuf:"varint,3,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMoveReq) Reset() {
	*x = QueueMoveReq{}
	mi := &file_proto_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMoveReq) ProtoMessage() {}

func (x *QueueMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMoveReq.ProtoReflect.Descriptor instead.
func (*QueueMoveReq) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{2}
}

func (x *QueueMoveReq) GetFromPosition() int32 {
	if x != nil {
		return x.FromPosition
	}
	return 0
}

func (x *QueueMoveReq) GetToPosition() int32 {
	if x != nil {
		return x.ToPosition
	}
	return 0
}

func (x *QueueMoveReq) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type QueueSetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*QueueSetEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	QueueId       int32                  `protobuf:"varint,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueSetReq) Reset() {
	*x = QueueSetReq{}
	mi := &file_proto_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueSetReq) ProtoMessage() {}

func (x *QueueSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueSetReq.ProtoReflect.Descriptor instead.
func (*QueueSetReq) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{3}
}

func (x *QueueSetReq) GetEntries() []*QueueSetEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueueSetReq) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type QueueSetEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TargetCycles  int32                  `protobuf:"varint,2,opt,name=target_cycles,json=targetCycles,proto3" json:"target_cycles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueSetEntry) Reset() {
	*x = QueueSetEntry{}
	mi := &file_proto_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueSetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueSetEntry) ProtoMessage() {}

func (x *QueueSetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueSetEntry.ProtoReflect.Descriptor instead.
func (*QueueSetEntry) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{4}
}

func (x *QueueSetEntry) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *QueueSetEntry) GetTargetCycles() int32 {
	if x != nil {
		return x.TargetCycles
	}
	return 0
}

var File_proto_queue_proto protoreflect.FileDescriptor

const file_proto_queue_proto_rawDesc = "" +
	"\n" +
	"\x11proto/queue.proto\x12\x06mli.v1\"k\n" +
	"\x0eQueueAppendReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12#\n" +
	"\rtarget_cycles\x18\x02 \x01(\x05R\ftargetCycles\x12\x19\n" +
	"\bqueue_id\x18\x03 \x01(\x05R\aqueueId\"G\n" +
	"\x0eQueueRemoveReq\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\x05R\aqueueId\"o\n" +
	"\fQueueMoveReq\x12#\n" +
	"\rfrom_position\x18\x01 \x01(\x05R\ffromPosition\x12\x1f\n" +
	"\vto_position\x18\x02 \x01(\x05R\n" +
	"toPosition\x12\x19\n" +
	"\bqueue_id\x18\x03 \x01(\x05R\aqueueId\"Y\n" +
	"\vQueueSetReq\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.mli.v1.QueueSetEntryR\aentries\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\x05R\aqueueId\"O\n" +
	"\rQueueSetEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12#\n" +
	"\rtarget_cycles\x18\x02 \x01(\x05R\ftargetCyclesB2Z0github.com/edrowsluo/new-mli/backend/internal/pbb\x06proto3"

var (
	file_proto_queue_proto_rawDescOnce sync.Once
	file_proto_queue_proto_rawDescData []byte
)

func file_proto_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_proto_rawDesc), len(file_proto_queue_proto_rawDesc)))
	})
	return file_proto_queue_proto_rawDescData
}

var file_proto_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_queue_proto_goTypes = []any{
	(*QueueAppendReq)(nil), // 0: mli.v1.QueueAppendReq
	(*QueueRemoveReq)(nil), // 1: mli.v1.QueueRemoveReq
	(*QueueMoveReq)(nil),   // 2: mli.v1.QueueMoveReq
	(*QueueSetReq)(nil),    // 3: mli.v1.QueueSetReq
	(*QueueSetEntry)(nil),  // 4: mli.v1.QueueSetEntry
}
var file_proto_queue_proto_depIdxs = []int32{
	4, // 0: mli.v1.QueueSetReq.entries:type_name -> mli.v1.QueueSetEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_queue_proto_init() }
func file_proto_queue_proto_init() {
	if File_proto_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_proto_rawDesc), len(file_proto_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_proto_depIdxs,
		MessageInfos:      file_proto_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_proto = out.File
	file_proto_queue_proto_goTypes = nil
	file_proto_queue_proto_depIdxs = nil
}
