// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: state.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryChangeReason int32

const (
	InventoryChangeReason_INVENTORY_CHANGE_UNSPECIFIED InventoryChangeReason = 0
	InventoryChangeReason_EVENT                        InventoryChangeReason = 1
	InventoryChangeReason_EQUIP                        InventoryChangeReason = 2
	InventoryChangeReason_UNEQUIP                      InventoryChangeReason = 3
)

// Enum value maps for InventoryChangeReason.
var (
	InventoryChangeReason_name = map[int32]string{
		0: "INVENTORY_CHANGE_UNSPECIFIED",
		1: "EVENT",
		2: "EQUIP",
		3: "UNEQUIP",
	}
	InventoryChangeReason_value = map[string]int32{
		"INVENTORY_CHANGE_UNSPECIFIED": 0,
		"EVENT":                        1,
		"EQUIP":                        2,
		"UNEQUIP":                      3,
	}
)

func (x InventoryChangeReason) Enum() *InventoryChangeReason {
	p := new(InventoryChangeReason)
	*p = x
	return p
}

func (x InventoryChangeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryChangeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (InventoryChangeReason) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x InventoryChangeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryChangeReason.Descriptor instead.
func (InventoryChangeReason) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

// -- Equipment --
type EquipAction int32

const (
	EquipAction_EQUIP_ACTION_UNSPECIFIED EquipAction = 0
	EquipAction_EQUIP_ACTION_EQUIP       EquipAction = 1
	EquipAction_EQUIP_ACTION_UNEQUIP     EquipAction = 2
)

// Enum value maps for EquipAction.
var (
	EquipAction_name = map[int32]string{
		0: "EQUIP_ACTION_UNSPECIFIED",
		1: "EQUIP_ACTION_EQUIP",
		2: "EQUIP_ACTION_UNEQUIP",
	}
	EquipAction_value = map[string]int32{
		"EQUIP_ACTION_UNSPECIFIED": 0,
		"EQUIP_ACTION_EQUIP":       1,
		"EQUIP_ACTION_UNEQUIP":     2,
	}
)

func (x EquipAction) Enum() *EquipAction {
	p := new(EquipAction)
	*p = x
	return p
}

func (x EquipAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EquipAction) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[1].Descriptor()
}

func (EquipAction) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[1]
}

func (x EquipAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EquipAction.Descriptor instead.
func (EquipAction) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

type ItemIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemState     int32                  `protobuf:"varint,2,opt,name=item_state,json=itemState,proto3" json:"item_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemIdentity) Reset() {
	*x = ItemIdentity{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemIdentity) ProtoMessage() {}

func (x *ItemIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemIdentity.ProtoReflect.Descriptor instead.
func (*ItemIdentity) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *ItemIdentity) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemIdentity) GetItemState() int32 {
	if x != nil {
		return x.ItemState
	}
	return 0
}

// -- Inventory --
type InventoryDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemState     int32                  `protobuf:"varint,2,opt,name=item_state,json=itemState,proto3" json:"item_state,omitempty"`
	QuantityDelta float64                `protobuf:"fixed64,3,opt,name=quantity_delta,json=quantityDelta,proto3" json:"quantity_delta,omitempty"`
	Reason        InventoryChangeReason  `protobuf:"varint,4,opt,name=reason,proto3,enum=mli.v1.InventoryChangeReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryDiff) Reset() {
	*x = InventoryDiff{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryDiff) ProtoMessage() {}

func (x *InventoryDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryDiff.ProtoReflect.Descriptor instead.
func (*InventoryDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryDiff) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *InventoryDiff) GetItemState() int32 {
	if x != nil {
		return x.ItemState
	}
	return 0
}

func (x *InventoryDiff) GetQuantityDelta() float64 {
	if x != nil {
		return x.QuantityDelta
	}
	return 0
}

func (x *InventoryDiff) GetReason() InventoryChangeReason {
	if x != nil {
		return x.Reason
	}
	return InventoryChangeReason_INVENTORY_CHANGE_UNSPECIFIED
}

type InventoryFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemState     int32                  `protobuf:"varint,2,opt,name=item_state,json=itemState,proto3" json:"item_state,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryFull) Reset() {
	*x = InventoryFull{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryFull) ProtoMessage() {}

func (x *InventoryFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryFull.ProtoReflect.Descriptor instead.
func (*InventoryFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryFull) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *InventoryFull) GetItemState() int32 {
	if x != nil {
		return x.ItemState
	}
	return 0
}

func (x *InventoryFull) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// -- Attribute --
type ModifierWire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	RefAttr       string                 `protobuf:"bytes,4,opt,name=ref_attr,json=refAttr,proto3" json:"ref_attr,omitempty"`
	Display       string                 `protobuf:"bytes,5,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifierWire) Reset() {
	*x = ModifierWire{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifierWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifierWire) ProtoMessage() {}

func (x *ModifierWire) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifierWire.ProtoReflect.Descriptor instead.
func (*ModifierWire) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *ModifierWire) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ModifierWire) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ModifierWire) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ModifierWire) GetRefAttr() string {
	if x != nil {
		return x.RefAttr
	}
	return ""
}

func (x *ModifierWire) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

type AttributeDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrId        string                 `protobuf:"bytes,1,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	FinalValue    float64                `protobuf:"fixed64,2,opt,name=final_value,json=finalValue,proto3" json:"final_value,omitempty"`
	Modifiers     []*ModifierWire        `protobuf:"bytes,3,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDiff) Reset() {
	*x = AttributeDiff{}
	mi := &file_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDiff) ProtoMessage() {}

func (x *AttributeDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDiff.ProtoReflect.Descriptor instead.
func (*AttributeDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeDiff) GetAttrId() string {
	if x != nil {
		return x.AttrId
	}
	return ""
}

func (x *AttributeDiff) GetFinalValue() float64 {
	if x != nil {
		return x.FinalValue
	}
	return 0
}

func (x *AttributeDiff) GetModifiers() []*ModifierWire {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type AttributeFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrId        string                 `protobuf:"bytes,1,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FinalValue    float64                `protobuf:"fixed64,3,opt,name=final_value,json=finalValue,proto3" json:"final_value,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Modifiers     []*ModifierWire        `protobuf:"bytes,6,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeFull) Reset() {
	*x = AttributeFull{}
	mi := &file_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeFull) ProtoMessage() {}

func (x *AttributeFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeFull.ProtoReflect.Descriptor instead.
func (*AttributeFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeFull) GetAttrId() string {
	if x != nil {
		return x.AttrId
	}
	return ""
}

func (x *AttributeFull) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeFull) GetFinalValue() float64 {
	if x != nil {
		return x.FinalValue
	}
	return 0
}

func (x *AttributeFull) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AttributeFull) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *AttributeFull) GetModifiers() []*ModifierWire {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

// -- Skill XP --
type SkillXPDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int64                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	XpDelta       float64                `protobuf:"fixed64,2,opt,name=xp_delta,json=xpDelta,proto3" json:"xp_delta,omitempty"`
	NewLevel      float64                `protobuf:"fixed64,3,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillXPDiff) Reset() {
	*x = SkillXPDiff{}
	mi := &file_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillXPDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillXPDiff) ProtoMessage() {}

func (x *SkillXPDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillXPDiff.ProtoReflect.Descriptor instead.
func (*SkillXPDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *SkillXPDiff) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillXPDiff) GetXpDelta() float64 {
	if x != nil {
		return x.XpDelta
	}
	return 0
}

func (x *SkillXPDiff) GetNewLevel() float64 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

type SkillXPFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int64                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Level         float64                `protobuf:"fixed64,2,opt,name=level,proto3" json:"level,omitempty"`
	Xp            float64                `protobuf:"fixed64,3,opt,name=xp,proto3" json:"xp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillXPFull) Reset() {
	*x = SkillXPFull{}
	mi := &file_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillXPFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillXPFull) ProtoMessage() {}

func (x *SkillXPFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillXPFull.ProtoReflect.Descriptor instead.
func (*SkillXPFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *SkillXPFull) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillXPFull) GetLevel() float64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SkillXPFull) GetXp() float64 {
	if x != nil {
		return x.Xp
	}
	return 0
}

// -- Bestiary --
type BestiaryDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestiaryDiff) Reset() {
	*x = BestiaryDiff{}
	mi := &file_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestiaryDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestiaryDiff) ProtoMessage() {}

func (x *BestiaryDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestiaryDiff.ProtoReflect.Descriptor instead.
func (*BestiaryDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{8}
}

func (x *BestiaryDiff) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BestiaryDiff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BestiaryFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestiaryFull) Reset() {
	*x = BestiaryFull{}
	mi := &file_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestiaryFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestiaryFull) ProtoMessage() {}

func (x *BestiaryFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestiaryFull.ProtoReflect.Descriptor instead.
func (*BestiaryFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{9}
}

func (x *BestiaryFull) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BestiaryFull) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// -- Event Execution --
type EventExecutionDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Cycles        int32                  `protobuf:"varint,2,opt,name=cycles,proto3" json:"cycles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventExecutionDiff) Reset() {
	*x = EventExecutionDiff{}
	mi := &file_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventExecutionDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventExecutionDiff) ProtoMessage() {}

func (x *EventExecutionDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventExecutionDiff.ProtoReflect.Descriptor instead.
func (*EventExecutionDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{10}
}

func (x *EventExecutionDiff) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventExecutionDiff) GetCycles() int32 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

type EventExecutionFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       int32                  `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TargetCycles  int32                  `protobuf:"varint,3,opt,name=target_cycles,json=targetCycles,proto3" json:"target_cycles,omitempty"`
	Progress      float64                `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventExecutionFull) Reset() {
	*x = EventExecutionFull{}
	mi := &file_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventExecutionFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventExecutionFull) ProtoMessage() {}

func (x *EventExecutionFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventExecutionFull.ProtoReflect.Descriptor instead.
func (*EventExecutionFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{11}
}

func (x *EventExecutionFull) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *EventExecutionFull) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventExecutionFull) GetTargetCycles() int32 {
	if x != nil {
		return x.TargetCycles
	}
	return 0
}

func (x *EventExecutionFull) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// -- Event Queue --
type EventQueueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TargetCycles  int32                  `protobuf:"varint,3,opt,name=target_cycles,json=targetCycles,proto3" json:"target_cycles,omitempty"`
	Progress      float64                `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQueueEntry) Reset() {
	*x = EventQueueEntry{}
	mi := &file_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQueueEntry) ProtoMessage() {}

func (x *EventQueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQueueEntry.ProtoReflect.Descriptor instead.
func (*EventQueueEntry) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{12}
}

func (x *EventQueueEntry) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *EventQueueEntry) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventQueueEntry) GetTargetCycles() int32 {
	if x != nil {
		return x.TargetCycles
	}
	return 0
}

func (x *EventQueueEntry) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type EventQueueDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       int32                  `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // "current" or "full"
	Entries       []*EventQueueEntry     `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQueueDiff) Reset() {
	*x = EventQueueDiff{}
	mi := &file_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQueueDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQueueDiff) ProtoMessage() {}

func (x *EventQueueDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQueueDiff.ProtoReflect.Descriptor instead.
func (*EventQueueDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{13}
}

func (x *EventQueueDiff) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *EventQueueDiff) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *EventQueueDiff) GetEntries() []*EventQueueEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type EquipmentDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemState     int32                  `protobuf:"varint,3,opt,name=item_state,json=itemState,proto3" json:"item_state,omitempty"`
	Action        EquipAction            `protobuf:"varint,4,opt,name=action,proto3,enum=mli.v1.EquipAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentDiff) Reset() {
	*x = EquipmentDiff{}
	mi := &file_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDiff) ProtoMessage() {}

func (x *EquipmentDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDiff.ProtoReflect.Descriptor instead.
func (*EquipmentDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{14}
}

func (x *EquipmentDiff) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *EquipmentDiff) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipmentDiff) GetItemState() int32 {
	if x != nil {
		return x.ItemState
	}
	return 0
}

func (x *EquipmentDiff) GetAction() EquipAction {
	if x != nil {
		return x.Action
	}
	return EquipAction_EQUIP_ACTION_UNSPECIFIED
}

// -- State envelopes --
type StateDiff struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Inventory      []*InventoryDiff       `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	Attribute      []*AttributeDiff       `protobuf:"bytes,2,rep,name=attribute,proto3" json:"attribute,omitempty"`
	SkillXp        []*SkillXPDiff         `protobuf:"bytes,3,rep,name=skill_xp,json=skillXp,proto3" json:"skill_xp,omitempty"`
	Bestiary       []*BestiaryDiff        `protobuf:"bytes,4,rep,name=bestiary,proto3" json:"bestiary,omitempty"`
	EventExecution []*EventExecutionDiff  `protobuf:"bytes,5,rep,name=event_execution,json=eventExecution,proto3" json:"event_execution,omitempty"`
	EventQueue     []*EventQueueDiff      `protobuf:"bytes,6,rep,name=event_queue,json=eventQueue,proto3" json:"event_queue,omitempty"`
	Equipment      []*EquipmentDiff       `protobuf:"bytes,7,rep,name=equipment,proto3" json:"equipment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateDiff) Reset() {
	*x = StateDiff{}
	mi := &file_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateDiff) ProtoMessage() {}

func (x *StateDiff) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateDiff.ProtoReflect.Descriptor instead.
func (*StateDiff) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{15}
}

func (x *StateDiff) GetInventory() []*InventoryDiff {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *StateDiff) GetAttribute() []*AttributeDiff {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *StateDiff) GetSkillXp() []*SkillXPDiff {
	if x != nil {
		return x.SkillXp
	}
	return nil
}

func (x *StateDiff) GetBestiary() []*BestiaryDiff {
	if x != nil {
		return x.Bestiary
	}
	return nil
}

func (x *StateDiff) GetEventExecution() []*EventExecutionDiff {
	if x != nil {
		return x.EventExecution
	}
	return nil
}

func (x *StateDiff) GetEventQueue() []*EventQueueDiff {
	if x != nil {
		return x.EventQueue
	}
	return nil
}

func (x *StateDiff) GetEquipment() []*EquipmentDiff {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type StateFull struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Inventory      []*InventoryFull         `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	Attribute      []*AttributeFull         `protobuf:"bytes,2,rep,name=attribute,proto3" json:"attribute,omitempty"`
	SkillXp        []*SkillXPFull           `protobuf:"bytes,3,rep,name=skill_xp,json=skillXp,proto3" json:"skill_xp,omitempty"`
	Bestiary       []*BestiaryFull          `protobuf:"bytes,4,rep,name=bestiary,proto3" json:"bestiary,omitempty"`
	EventExecution []*EventExecutionFull    `protobuf:"bytes,5,rep,name=event_execution,json=eventExecution,proto3" json:"event_execution,omitempty"`
	Equipment      map[string]*ItemIdentity `protobuf:"bytes,6,rep,name=equipment,proto3" json:"equipment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateFull) Reset() {
	*x = StateFull{}
	mi := &file_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateFull) ProtoMessage() {}

func (x *StateFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateFull.ProtoReflect.Descriptor instead.
func (*StateFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{16}
}

func (x *StateFull) GetInventory() []*InventoryFull {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *StateFull) GetAttribute() []*AttributeFull {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *StateFull) GetSkillXp() []*SkillXPFull {
	if x != nil {
		return x.SkillXp
	}
	return nil
}

func (x *StateFull) GetBestiary() []*BestiaryFull {
	if x != nil {
		return x.Bestiary
	}
	return nil
}

func (x *StateFull) GetEventExecution() []*EventExecutionFull {
	if x != nil {
		return x.EventExecution
	}
	return nil
}

func (x *StateFull) GetEquipment() map[string]*ItemIdentity {
	if x != nil {
		return x.Equipment
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x06mli.v1\"F\n" +
	"\fItemIdentity\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_state\x18\x02 \x01(\x05R\titemState\"\xa5\x01\n" +
	"\rInventoryDiff\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_state\x18\x02 \x01(\x05R\titemState\x12%\n" +
	"\x0equantity_delta\x18\x03 \x01(\x01R\rquantityDelta\x125\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1d.mli.v1.InventoryChangeReasonR\x06reason\"c\n" +
	"\rInventoryFull\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_state\x18\x02 \x01(\x05R\titemState\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\"\x81\x01\n" +
	"\fModifierWire\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x19\n" +
	"\bref_attr\x18\x04 \x01(\tR\arefAttr\x12\x18\n" +
	"\adisplay\x18\x05 \x01(\tR\adisplay\"}\n" +
	"\rAttributeDiff\x12\x17\n" +
	"\aattr_id\x18\x01 \x01(\tR\x06attrId\x12\x1f\n" +
	"\vfinal_value\x18\x02 \x01(\x01R\n" +
	"finalValue\x122\n" +
	"\tmodifiers\x18\x03 \x03(\v2\x14.mli.v1.ModifierWireR\tmodifiers\"\xc5\x01\n" +
	"\rAttributeFull\x12\x17\n" +
	"\aattr_id\x18\x01 \x01(\tR\x06attrId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfinal_value\x18\x03 \x01(\x01R\n" +
	"finalValue\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x122\n" +
	"\tmodifiers\x18\x06 \x03(\v2\x14.mli.v1.ModifierWireR\tmodifiers\"`\n" +
	"\vSkillXPDiff\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x03R\askillId\x12\x19\n" +
	"\bxp_delta\x18\x02 \x01(\x01R\axpDelta\x12\x1b\n" +
	"\tnew_level\x18\x03 \x01(\x01R\bnewLevel\"N\n" +
	"\vSkillXPFull\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x03R\askillId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x01R\x05level\x12\x0e\n" +
	"\x02xp\x18\x03 \x01(\x01R\x02xp\"2\n" +
	"\fBestiaryDiff\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\fBestiaryFull\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"G\n" +
	"\x12EventExecutionDiff\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x16\n" +
	"\x06cycles\x18\x02 \x01(\x05R\x06cycles\"\x8b\x01\n" +
	"\x12EventExecutionFull\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\x05R\aqueueId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12#\n" +
	"\rtarget_cycles\x18\x03 \x01(\x05R\ftargetCycles\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x01R\bprogress\"\x89\x01\n" +
	"\x0fEventQueueEntry\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12#\n" +
	"\rtarget_cycles\x18\x03 \x01(\x05R\ftargetCycles\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x01R\bprogress\"t\n" +
	"\x0eEventQueueDiff\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\x05R\aqueueId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.mli.v1.EventQueueEntryR\aentries\"\x88\x01\n" +
	"\rEquipmentDiff\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_state\x18\x03 \x01(\x05R\titemState\x12+\n" +
	"\x06action\x18\x04 \x01(\x0e2\x13.mli.v1.EquipActionR\x06action\"\x8a\x03\n" +
	"\tStateDiff\x123\n" +
	"\tinventory\x18\x01 \x03(\v2\x15.mli.v1.InventoryDiffR\tinventory\x123\n" +
	"\tattribute\x18\x02 \x03(\v2\x15.mli.v1.AttributeDiffR\tattribute\x12.\n" +
	"\bskill_xp\x18\x03 \x03(\v2\x13.mli.v1.SkillXPDiffR\askillXp\x120\n" +
	"\bbestiary\x18\x04 \x03(\v2\x14.mli.v1.BestiaryDiffR\bbestiary\x12C\n" +
	"\x0fevent_execution\x18\x05 \x03(\v2\x1a.mli.v1.EventExecutionDiffR\x0eeventExecution\x127\n" +
	"\vevent_queue\x18\x06 \x03(\v2\x16.mli.v1.EventQueueDiffR\n" +
	"eventQueue\x123\n" +
	"\tequipment\x18\a \x03(\v2\x15.mli.v1.EquipmentDiffR\tequipment\"\xb0\x03\n" +
	"\tStateFull\x123\n" +
	"\tinventory\x18\x01 \x03(\v2\x15.mli.v1.InventoryFullR\tinventory\x123\n" +
	"\tattribute\x18\x02 \x03(\v2\x15.mli.v1.AttributeFullR\tattribute\x12.\n" +
	"\bskill_xp\x18\x03 \x03(\v2\x13.mli.v1.SkillXPFullR\askillXp\x120\n" +
	"\bbestiary\x18\x04 \x03(\v2\x14.mli.v1.BestiaryFullR\bbestiary\x12C\n" +
	"\x0fevent_execution\x18\x05 \x03(\v2\x1a.mli.v1.EventExecutionFullR\x0eeventExecution\x12>\n" +
	"\tequipment\x18\x06 \x03(\v2 .mli.v1.StateFull.EquipmentEntryR\tequipment\x1aR\n" +
	"\x0eEquipmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.mli.v1.ItemIdentityR\x05value:\x028\x01*\\\n" +
	"\x15InventoryChangeReason\x12 \n" +
	"\x1cINVENTORY_CHANGE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\t\n" +
	"\x05EQUIP\x10\x02\x12\v\n" +
	"\aUNEQUIP\x10\x03*]\n" +
	"\vEquipAction\x12\x1c\n" +
	"\x18EQUIP_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EQUIP_ACTION_EQUIP\x10\x01\x12\x18\n" +
	"\x14EQUIP_ACTION_UNEQUIP\x10\x02BNZLgithub.com/Milkyway-Liluo-Idle-Develop-Team/Milkyway-Liluo-Idle-2/backend/pbb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_state_proto_goTypes = []any{
	(InventoryChangeReason)(0), // 0: mli.v1.InventoryChangeReason
	(EquipAction)(0),           // 1: mli.v1.EquipAction
	(*ItemIdentity)(nil),       // 2: mli.v1.ItemIdentity
	(*InventoryDiff)(nil),      // 3: mli.v1.InventoryDiff
	(*InventoryFull)(nil),      // 4: mli.v1.InventoryFull
	(*ModifierWire)(nil),       // 5: mli.v1.ModifierWire
	(*AttributeDiff)(nil),      // 6: mli.v1.AttributeDiff
	(*AttributeFull)(nil),      // 7: mli.v1.AttributeFull
	(*SkillXPDiff)(nil),        // 8: mli.v1.SkillXPDiff
	(*SkillXPFull)(nil),        // 9: mli.v1.SkillXPFull
	(*BestiaryDiff)(nil),       // 10: mli.v1.BestiaryDiff
	(*BestiaryFull)(nil),       // 11: mli.v1.BestiaryFull
	(*EventExecutionDiff)(nil), // 12: mli.v1.EventExecutionDiff
	(*EventExecutionFull)(nil), // 13: mli.v1.EventExecutionFull
	(*EventQueueEntry)(nil),    // 14: mli.v1.EventQueueEntry
	(*EventQueueDiff)(nil),     // 15: mli.v1.EventQueueDiff
	(*EquipmentDiff)(nil),      // 16: mli.v1.EquipmentDiff
	(*StateDiff)(nil),          // 17: mli.v1.StateDiff
	(*StateFull)(nil),          // 18: mli.v1.StateFull
	nil,                        // 19: mli.v1.StateFull.EquipmentEntry
}
var file_state_proto_depIdxs = []int32{
	0,  // 0: mli.v1.InventoryDiff.reason:type_name -> mli.v1.InventoryChangeReason
	5,  // 1: mli.v1.AttributeDiff.modifiers:type_name -> mli.v1.ModifierWire
	5,  // 2: mli.v1.AttributeFull.modifiers:type_name -> mli.v1.ModifierWire
	14, // 3: mli.v1.EventQueueDiff.entries:type_name -> mli.v1.EventQueueEntry
	1,  // 4: mli.v1.EquipmentDiff.action:type_name -> mli.v1.EquipAction
	3,  // 5: mli.v1.StateDiff.inventory:type_name -> mli.v1.InventoryDiff
	6,  // 6: mli.v1.StateDiff.attribute:type_name -> mli.v1.AttributeDiff
	8,  // 7: mli.v1.StateDiff.skill_xp:type_name -> mli.v1.SkillXPDiff
	10, // 8: mli.v1.StateDiff.bestiary:type_name -> mli.v1.BestiaryDiff
	12, // 9: mli.v1.StateDiff.event_execution:type_name -> mli.v1.EventExecutionDiff
	15, // 10: mli.v1.StateDiff.event_queue:type_name -> mli.v1.EventQueueDiff
	16, // 11: mli.v1.StateDiff.equipment:type_name -> mli.v1.EquipmentDiff
	4,  // 12: mli.v1.StateFull.inventory:type_name -> mli.v1.InventoryFull
	7,  // 13: mli.v1.StateFull.attribute:type_name -> mli.v1.AttributeFull
	9,  // 14: mli.v1.StateFull.skill_xp:type_name -> mli.v1.SkillXPFull
	11, // 15: mli.v1.StateFull.bestiary:type_name -> mli.v1.BestiaryFull
	13, // 16: mli.v1.StateFull.event_execution:type_name -> mli.v1.EventExecutionFull
	19, // 17: mli.v1.StateFull.equipment:type_name -> mli.v1.StateFull.EquipmentEntry
	2,  // 18: mli.v1.StateFull.EquipmentEntry.value:type_name -> mli.v1.ItemIdentity
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
