// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v5.29.3
// source: equipment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ItemIdentity } from "./state.js";

export interface EquipReq {
  itemId?: number | undefined;
  itemState?: number | undefined;
  slot?: string | undefined;
}

export interface UnequipReq {
  slot?: string | undefined;
}

export interface EquipUnequipResponse {
  equipped?: { [key: string]: ItemIdentity } | undefined;
}

export interface EquipUnequipResponse_EquippedEntry {
  key: string;
  value?: ItemIdentity | undefined;
}

function createBaseEquipReq(): EquipReq {
  return { itemId: 0, itemState: 0, slot: "" };
}

export const EquipReq: MessageFns<EquipReq> = {
  encode(message: EquipReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== undefined && message.itemId !== 0) {
      writer.uint32(8).int32(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      writer.uint32(16).int32(message.itemState);
    }
    if (message.slot !== undefined && message.slot !== "") {
      writer.uint32(26).string(message.slot);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EquipReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEquipReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.itemId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemState = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.slot = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EquipReq {
    return {
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
        ? globalThis.Number(object.item_id)
        : 0,
      itemState: isSet(object.itemState)
        ? globalThis.Number(object.itemState)
        : isSet(object.item_state)
        ? globalThis.Number(object.item_state)
        : 0,
      slot: isSet(object.slot) ? globalThis.String(object.slot) : "",
    };
  },

  toJSON(message: EquipReq): unknown {
    const obj: any = {};
    if (message.itemId !== undefined && message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      obj.itemState = Math.round(message.itemState);
    }
    if (message.slot !== undefined && message.slot !== "") {
      obj.slot = message.slot;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EquipReq>, I>>(base?: I): EquipReq {
    return EquipReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EquipReq>, I>>(object: I): EquipReq {
    const message = createBaseEquipReq();
    message.itemId = object.itemId ?? 0;
    message.itemState = object.itemState ?? 0;
    message.slot = object.slot ?? "";
    return message;
  },
};

function createBaseUnequipReq(): UnequipReq {
  return { slot: "" };
}

export const UnequipReq: MessageFns<UnequipReq> = {
  encode(message: UnequipReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slot !== undefined && message.slot !== "") {
      writer.uint32(10).string(message.slot);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnequipReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnequipReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slot = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnequipReq {
    return { slot: isSet(object.slot) ? globalThis.String(object.slot) : "" };
  },

  toJSON(message: UnequipReq): unknown {
    const obj: any = {};
    if (message.slot !== undefined && message.slot !== "") {
      obj.slot = message.slot;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnequipReq>, I>>(base?: I): UnequipReq {
    return UnequipReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnequipReq>, I>>(object: I): UnequipReq {
    const message = createBaseUnequipReq();
    message.slot = object.slot ?? "";
    return message;
  },
};

function createBaseEquipUnequipResponse(): EquipUnequipResponse {
  return { equipped: {} };
}

export const EquipUnequipResponse: MessageFns<EquipUnequipResponse> = {
  encode(message: EquipUnequipResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.equipped || {}).forEach(([key, value]: [string, ItemIdentity]) => {
      EquipUnequipResponse_EquippedEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EquipUnequipResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEquipUnequipResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = EquipUnequipResponse_EquippedEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.equipped![entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EquipUnequipResponse {
    return {
      equipped: isObject(object.equipped)
        ? (globalThis.Object.entries(object.equipped) as [string, any][]).reduce(
          (acc: { [key: string]: ItemIdentity }, [key, value]: [string, any]) => {
            acc[key] = ItemIdentity.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: EquipUnequipResponse): unknown {
    const obj: any = {};
    if (message.equipped) {
      const entries = globalThis.Object.entries(message.equipped) as [string, ItemIdentity][];
      if (entries.length > 0) {
        obj.equipped = {};
        entries.forEach(([k, v]) => {
          obj.equipped[k] = ItemIdentity.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EquipUnequipResponse>, I>>(base?: I): EquipUnequipResponse {
    return EquipUnequipResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EquipUnequipResponse>, I>>(object: I): EquipUnequipResponse {
    const message = createBaseEquipUnequipResponse();
    message.equipped = (globalThis.Object.entries(object.equipped ?? {}) as [string, ItemIdentity][]).reduce(
      (acc: { [key: string]: ItemIdentity }, [key, value]: [string, ItemIdentity]) => {
        if (value !== undefined) {
          acc[key] = ItemIdentity.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseEquipUnequipResponse_EquippedEntry(): EquipUnequipResponse_EquippedEntry {
  return { key: "", value: undefined };
}

export const EquipUnequipResponse_EquippedEntry: MessageFns<EquipUnequipResponse_EquippedEntry> = {
  encode(message: EquipUnequipResponse_EquippedEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      ItemIdentity.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EquipUnequipResponse_EquippedEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEquipUnequipResponse_EquippedEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ItemIdentity.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EquipUnequipResponse_EquippedEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? ItemIdentity.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: EquipUnequipResponse_EquippedEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ItemIdentity.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EquipUnequipResponse_EquippedEntry>, I>>(
    base?: I,
  ): EquipUnequipResponse_EquippedEntry {
    return EquipUnequipResponse_EquippedEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EquipUnequipResponse_EquippedEntry>, I>>(
    object: I,
  ): EquipUnequipResponse_EquippedEntry {
    const message = createBaseEquipUnequipResponse_EquippedEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ItemIdentity.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
