// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v5.29.3
// source: queue.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface QueueAppendReq {
  eventId?:
    | number
    | undefined;
  /** -1 = infinite */
  targetCycles?: number | undefined;
  queueId?: number | undefined;
}

export interface QueueRemoveReq {
  position?: number | undefined;
  queueId?: number | undefined;
}

export interface QueueMoveReq {
  fromPosition?: number | undefined;
  toPosition?: number | undefined;
  queueId?: number | undefined;
}

export interface QueueSetReq {
  entries?: QueueSetEntry[] | undefined;
  queueId?: number | undefined;
}

export interface QueueSetEntry {
  eventId?: number | undefined;
  targetCycles?: number | undefined;
}

function createBaseQueueAppendReq(): QueueAppendReq {
  return { eventId: 0, targetCycles: 0, queueId: 0 };
}

export const QueueAppendReq: MessageFns<QueueAppendReq> = {
  encode(message: QueueAppendReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== undefined && message.eventId !== 0) {
      writer.uint32(8).int64(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      writer.uint32(16).int32(message.targetCycles);
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      writer.uint32(24).int32(message.queueId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueAppendReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueAppendReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.targetCycles = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.queueId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueueAppendReq {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      targetCycles: isSet(object.targetCycles)
        ? globalThis.Number(object.targetCycles)
        : isSet(object.target_cycles)
        ? globalThis.Number(object.target_cycles)
        : 0,
      queueId: isSet(object.queueId)
        ? globalThis.Number(object.queueId)
        : isSet(object.queue_id)
        ? globalThis.Number(object.queue_id)
        : 0,
    };
  },

  toJSON(message: QueueAppendReq): unknown {
    const obj: any = {};
    if (message.eventId !== undefined && message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      obj.targetCycles = Math.round(message.targetCycles);
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      obj.queueId = Math.round(message.queueId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueAppendReq>, I>>(base?: I): QueueAppendReq {
    return QueueAppendReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueAppendReq>, I>>(object: I): QueueAppendReq {
    const message = createBaseQueueAppendReq();
    message.eventId = object.eventId ?? 0;
    message.targetCycles = object.targetCycles ?? 0;
    message.queueId = object.queueId ?? 0;
    return message;
  },
};

function createBaseQueueRemoveReq(): QueueRemoveReq {
  return { position: 0, queueId: 0 };
}

export const QueueRemoveReq: MessageFns<QueueRemoveReq> = {
  encode(message: QueueRemoveReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== undefined && message.position !== 0) {
      writer.uint32(8).int32(message.position);
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      writer.uint32(16).int32(message.queueId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueRemoveReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueRemoveReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.position = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.queueId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueueRemoveReq {
    return {
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
      queueId: isSet(object.queueId)
        ? globalThis.Number(object.queueId)
        : isSet(object.queue_id)
        ? globalThis.Number(object.queue_id)
        : 0,
    };
  },

  toJSON(message: QueueRemoveReq): unknown {
    const obj: any = {};
    if (message.position !== undefined && message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      obj.queueId = Math.round(message.queueId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueRemoveReq>, I>>(base?: I): QueueRemoveReq {
    return QueueRemoveReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueRemoveReq>, I>>(object: I): QueueRemoveReq {
    const message = createBaseQueueRemoveReq();
    message.position = object.position ?? 0;
    message.queueId = object.queueId ?? 0;
    return message;
  },
};

function createBaseQueueMoveReq(): QueueMoveReq {
  return { fromPosition: 0, toPosition: 0, queueId: 0 };
}

export const QueueMoveReq: MessageFns<QueueMoveReq> = {
  encode(message: QueueMoveReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromPosition !== undefined && message.fromPosition !== 0) {
      writer.uint32(8).int32(message.fromPosition);
    }
    if (message.toPosition !== undefined && message.toPosition !== 0) {
      writer.uint32(16).int32(message.toPosition);
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      writer.uint32(24).int32(message.queueId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueMoveReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueMoveReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.fromPosition = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.toPosition = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.queueId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueueMoveReq {
    return {
      fromPosition: isSet(object.fromPosition)
        ? globalThis.Number(object.fromPosition)
        : isSet(object.from_position)
        ? globalThis.Number(object.from_position)
        : 0,
      toPosition: isSet(object.toPosition)
        ? globalThis.Number(object.toPosition)
        : isSet(object.to_position)
        ? globalThis.Number(object.to_position)
        : 0,
      queueId: isSet(object.queueId)
        ? globalThis.Number(object.queueId)
        : isSet(object.queue_id)
        ? globalThis.Number(object.queue_id)
        : 0,
    };
  },

  toJSON(message: QueueMoveReq): unknown {
    const obj: any = {};
    if (message.fromPosition !== undefined && message.fromPosition !== 0) {
      obj.fromPosition = Math.round(message.fromPosition);
    }
    if (message.toPosition !== undefined && message.toPosition !== 0) {
      obj.toPosition = Math.round(message.toPosition);
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      obj.queueId = Math.round(message.queueId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueMoveReq>, I>>(base?: I): QueueMoveReq {
    return QueueMoveReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueMoveReq>, I>>(object: I): QueueMoveReq {
    const message = createBaseQueueMoveReq();
    message.fromPosition = object.fromPosition ?? 0;
    message.toPosition = object.toPosition ?? 0;
    message.queueId = object.queueId ?? 0;
    return message;
  },
};

function createBaseQueueSetReq(): QueueSetReq {
  return { entries: [], queueId: 0 };
}

export const QueueSetReq: MessageFns<QueueSetReq> = {
  encode(message: QueueSetReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entries !== undefined && message.entries.length !== 0) {
      for (const v of message.entries) {
        QueueSetEntry.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      writer.uint32(16).int32(message.queueId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueSetReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueSetReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = QueueSetEntry.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.entries!.push(el);
          }
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.queueId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueueSetReq {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => QueueSetEntry.fromJSON(e))
        : [],
      queueId: isSet(object.queueId)
        ? globalThis.Number(object.queueId)
        : isSet(object.queue_id)
        ? globalThis.Number(object.queue_id)
        : 0,
    };
  },

  toJSON(message: QueueSetReq): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => QueueSetEntry.toJSON(e));
    }
    if (message.queueId !== undefined && message.queueId !== 0) {
      obj.queueId = Math.round(message.queueId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueSetReq>, I>>(base?: I): QueueSetReq {
    return QueueSetReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueSetReq>, I>>(object: I): QueueSetReq {
    const message = createBaseQueueSetReq();
    message.entries = object.entries?.map((e) => QueueSetEntry.fromPartial(e)) || [];
    message.queueId = object.queueId ?? 0;
    return message;
  },
};

function createBaseQueueSetEntry(): QueueSetEntry {
  return { eventId: 0, targetCycles: 0 };
}

export const QueueSetEntry: MessageFns<QueueSetEntry> = {
  encode(message: QueueSetEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== undefined && message.eventId !== 0) {
      writer.uint32(8).int64(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      writer.uint32(16).int32(message.targetCycles);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueSetEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueSetEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.targetCycles = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueueSetEntry {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      targetCycles: isSet(object.targetCycles)
        ? globalThis.Number(object.targetCycles)
        : isSet(object.target_cycles)
        ? globalThis.Number(object.target_cycles)
        : 0,
    };
  },

  toJSON(message: QueueSetEntry): unknown {
    const obj: any = {};
    if (message.eventId !== undefined && message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      obj.targetCycles = Math.round(message.targetCycles);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueSetEntry>, I>>(base?: I): QueueSetEntry {
    return QueueSetEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueSetEntry>, I>>(object: I): QueueSetEntry {
    const message = createBaseQueueSetEntry();
    message.eventId = object.eventId ?? 0;
    message.targetCycles = object.targetCycles ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
