// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: equipment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EquipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemState     int32                  `protobuf:"varint,2,opt,name=item_state,json=itemState,proto3" json:"item_state,omitempty"`
	Slot          string                 `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipReq) Reset() {
	*x = EquipReq{}
	mi := &file_equipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipReq) ProtoMessage() {}

func (x *EquipReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipReq.ProtoReflect.Descriptor instead.
func (*EquipReq) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *EquipReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipReq) GetItemState() int32 {
	if x != nil {
		return x.ItemState
	}
	return 0
}

func (x *EquipReq) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type UnequipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipReq) Reset() {
	*x = UnequipReq{}
	mi := &file_equipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipReq) ProtoMessage() {}

func (x *UnequipReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipReq.ProtoReflect.Descriptor instead.
func (*UnequipReq) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *UnequipReq) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type EquipUnequipResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Equipped      map[string]*ItemIdentity `protobuf:"bytes,1,rep,name=equipped,proto3" json:"equipped,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipUnequipResponse) Reset() {
	*x = EquipUnequipResponse{}
	mi := &file_equipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipUnequipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipUnequipResponse) ProtoMessage() {}

func (x *EquipUnequipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipUnequipResponse.ProtoReflect.Descriptor instead.
func (*EquipUnequipResponse) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *EquipUnequipResponse) GetEquipped() map[string]*ItemIdentity {
	if x != nil {
		return x.Equipped
	}
	return nil
}

var File_equipment_proto protoreflect.FileDescriptor

const file_equipment_proto_rawDesc = "" +
	"\n" +
	"\x0fequipment.proto\x12\x06mli.v1\x1a\vstate.proto\"V\n" +
	"\bEquipReq\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_state\x18\x02 \x01(\x05R\titemState\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\tR\x04slot\" \n" +
	"\n" +
	"UnequipReq\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"\xb1\x01\n" +
	"\x14EquipUnequipResponse\x12F\n" +
	"\bequipped\x18\x01 \x03(\v2*.mli.v1.EquipUnequipResponse.EquippedEntryR\bequipped\x1aQ\n" +
	"\rEquippedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.mli.v1.ItemIdentityR\x05value:\x028\x01B2Z0github.com/edrowsluo/new-mli/backend/internal/pbb\x06proto3"

var (
	file_equipment_proto_rawDescOnce sync.Once
	file_equipment_proto_rawDescData []byte
)

func file_equipment_proto_rawDescGZIP() []byte {
	file_equipment_proto_rawDescOnce.Do(func() {
		file_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_equipment_proto_rawDesc), len(file_equipment_proto_rawDesc)))
	})
	return file_equipment_proto_rawDescData
}

var file_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_equipment_proto_goTypes = []any{
	(*EquipReq)(nil),             // 0: mli.v1.EquipReq
	(*UnequipReq)(nil),           // 1: mli.v1.UnequipReq
	(*EquipUnequipResponse)(nil), // 2: mli.v1.EquipUnequipResponse
	nil,                          // 3: mli.v1.EquipUnequipResponse.EquippedEntry
	(*ItemIdentity)(nil),         // 4: mli.v1.ItemIdentity
}
var file_equipment_proto_depIdxs = []int32{
	3, // 0: mli.v1.EquipUnequipResponse.equipped:type_name -> mli.v1.EquipUnequipResponse.EquippedEntry
	4, // 1: mli.v1.EquipUnequipResponse.EquippedEntry.value:type_name -> mli.v1.ItemIdentity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_equipment_proto_init() }
func file_equipment_proto_init() {
	if File_equipment_proto != nil {
		return
	}
	file_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_equipment_proto_rawDesc), len(file_equipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_equipment_proto_goTypes,
		DependencyIndexes: file_equipment_proto_depIdxs,
		MessageInfos:      file_equipment_proto_msgTypes,
	}.Build()
	File_equipment_proto = out.File
	file_equipment_proto_goTypes = nil
	file_equipment_proto_depIdxs = nil
}
