// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v5.29.3
// source: state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export enum InventoryChangeReason {
  INVENTORY_CHANGE_UNSPECIFIED = 0,
  EVENT = 1,
  EQUIP = 2,
  UNEQUIP = 3,
  UNRECOGNIZED = -1,
}

export function inventoryChangeReasonFromJSON(object: any): InventoryChangeReason {
  switch (object) {
    case 0:
    case "INVENTORY_CHANGE_UNSPECIFIED":
      return InventoryChangeReason.INVENTORY_CHANGE_UNSPECIFIED;
    case 1:
    case "EVENT":
      return InventoryChangeReason.EVENT;
    case 2:
    case "EQUIP":
      return InventoryChangeReason.EQUIP;
    case 3:
    case "UNEQUIP":
      return InventoryChangeReason.UNEQUIP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InventoryChangeReason.UNRECOGNIZED;
  }
}

export function inventoryChangeReasonToJSON(object: InventoryChangeReason): string {
  switch (object) {
    case InventoryChangeReason.INVENTORY_CHANGE_UNSPECIFIED:
      return "INVENTORY_CHANGE_UNSPECIFIED";
    case InventoryChangeReason.EVENT:
      return "EVENT";
    case InventoryChangeReason.EQUIP:
      return "EQUIP";
    case InventoryChangeReason.UNEQUIP:
      return "UNEQUIP";
    case InventoryChangeReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** -- Equipment -- */
export enum EquipAction {
  EQUIP_ACTION_UNSPECIFIED = 0,
  EQUIP_ACTION_EQUIP = 1,
  EQUIP_ACTION_UNEQUIP = 2,
  UNRECOGNIZED = -1,
}

export function equipActionFromJSON(object: any): EquipAction {
  switch (object) {
    case 0:
    case "EQUIP_ACTION_UNSPECIFIED":
      return EquipAction.EQUIP_ACTION_UNSPECIFIED;
    case 1:
    case "EQUIP_ACTION_EQUIP":
      return EquipAction.EQUIP_ACTION_EQUIP;
    case 2:
    case "EQUIP_ACTION_UNEQUIP":
      return EquipAction.EQUIP_ACTION_UNEQUIP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EquipAction.UNRECOGNIZED;
  }
}

export function equipActionToJSON(object: EquipAction): string {
  switch (object) {
    case EquipAction.EQUIP_ACTION_UNSPECIFIED:
      return "EQUIP_ACTION_UNSPECIFIED";
    case EquipAction.EQUIP_ACTION_EQUIP:
      return "EQUIP_ACTION_EQUIP";
    case EquipAction.EQUIP_ACTION_UNEQUIP:
      return "EQUIP_ACTION_UNEQUIP";
    case EquipAction.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ItemIdentity {
  itemId?: number | undefined;
  itemState?: number | undefined;
}

/** -- Inventory -- */
export interface InventoryDiff {
  itemId?: number | undefined;
  itemState?: number | undefined;
  quantityDelta?: number | undefined;
  reason?: InventoryChangeReason | undefined;
}

export interface InventoryFull {
  itemId?: number | undefined;
  itemState?: number | undefined;
  quantity?: number | undefined;
}

/** -- Attribute -- */
export interface ModifierWire {
  source?: string | undefined;
  op?: string | undefined;
  value?: number | undefined;
  refAttr?: string | undefined;
  display?: string | undefined;
}

export interface AttributeDiff {
  attrId?: string | undefined;
  finalValue?: number | undefined;
  modifiers?: ModifierWire[] | undefined;
}

export interface AttributeFull {
  attrId?: string | undefined;
  name?: string | undefined;
  finalValue?: number | undefined;
  group?: string | undefined;
  direction?: string | undefined;
  modifiers?: ModifierWire[] | undefined;
}

/** -- Skill XP -- */
export interface SkillXPDiff {
  skillId?: number | undefined;
  xpDelta?: number | undefined;
  newLevel?: number | undefined;
}

export interface SkillXPFull {
  skillId?: number | undefined;
  level?: number | undefined;
  xp?: number | undefined;
}

/** -- Bestiary -- */
export interface BestiaryDiff {
  type?: string | undefined;
  id?: string | undefined;
}

export interface BestiaryFull {
  type?: string | undefined;
  id?: string | undefined;
}

/** -- Event Execution -- */
export interface EventExecutionDiff {
  eventId?: number | undefined;
  cycles?: number | undefined;
}

export interface EventExecutionFull {
  queueId?: number | undefined;
  eventId?: number | undefined;
  targetCycles?: number | undefined;
  progress?: number | undefined;
}

/** -- Event Queue -- */
export interface EventQueueEntry {
  position?: number | undefined;
  eventId?: number | undefined;
  targetCycles?: number | undefined;
  progress?: number | undefined;
}

export interface EventQueueDiff {
  queueId?:
    | number
    | undefined;
  /** "current" or "full" */
  scope?: string | undefined;
  entries?: EventQueueEntry[] | undefined;
}

export interface EquipmentDiff {
  slot?: string | undefined;
  itemId?: number | undefined;
  itemState?: number | undefined;
  action?: EquipAction | undefined;
}

/** -- State envelopes -- */
export interface StateDiff {
  inventory?: InventoryDiff[] | undefined;
  attribute?: AttributeDiff[] | undefined;
  skillXp?: SkillXPDiff[] | undefined;
  bestiary?: BestiaryDiff[] | undefined;
  eventExecution?: EventExecutionDiff[] | undefined;
  eventQueue?: EventQueueDiff[] | undefined;
  equipment?: EquipmentDiff[] | undefined;
}

export interface StateFull {
  inventory?: InventoryFull[] | undefined;
  attribute?: AttributeFull[] | undefined;
  skillXp?: SkillXPFull[] | undefined;
  bestiary?: BestiaryFull[] | undefined;
  eventExecution?: EventExecutionFull[] | undefined;
  equipment?: { [key: string]: ItemIdentity } | undefined;
}

export interface StateFull_EquipmentEntry {
  key: string;
  value?: ItemIdentity | undefined;
}

function createBaseItemIdentity(): ItemIdentity {
  return { itemId: 0, itemState: 0 };
}

export const ItemIdentity: MessageFns<ItemIdentity> = {
  encode(message: ItemIdentity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== undefined && message.itemId !== 0) {
      writer.uint32(8).int32(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      writer.uint32(16).int32(message.itemState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemIdentity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemIdentity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.itemId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemState = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemIdentity {
    return {
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
        ? globalThis.Number(object.item_id)
        : 0,
      itemState: isSet(object.itemState)
        ? globalThis.Number(object.itemState)
        : isSet(object.item_state)
        ? globalThis.Number(object.item_state)
        : 0,
    };
  },

  toJSON(message: ItemIdentity): unknown {
    const obj: any = {};
    if (message.itemId !== undefined && message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      obj.itemState = Math.round(message.itemState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemIdentity>, I>>(base?: I): ItemIdentity {
    return ItemIdentity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemIdentity>, I>>(object: I): ItemIdentity {
    const message = createBaseItemIdentity();
    message.itemId = object.itemId ?? 0;
    message.itemState = object.itemState ?? 0;
    return message;
  },
};

function createBaseInventoryDiff(): InventoryDiff {
  return { itemId: 0, itemState: 0, quantityDelta: 0, reason: 0 };
}

export const InventoryDiff: MessageFns<InventoryDiff> = {
  encode(message: InventoryDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== undefined && message.itemId !== 0) {
      writer.uint32(8).int32(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      writer.uint32(16).int32(message.itemState);
    }
    if (message.quantityDelta !== undefined && message.quantityDelta !== 0) {
      writer.uint32(25).double(message.quantityDelta);
    }
    if (message.reason !== undefined && message.reason !== 0) {
      writer.uint32(32).int32(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InventoryDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInventoryDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.itemId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemState = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.quantityDelta = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.reason = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InventoryDiff {
    return {
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
        ? globalThis.Number(object.item_id)
        : 0,
      itemState: isSet(object.itemState)
        ? globalThis.Number(object.itemState)
        : isSet(object.item_state)
        ? globalThis.Number(object.item_state)
        : 0,
      quantityDelta: isSet(object.quantityDelta)
        ? globalThis.Number(object.quantityDelta)
        : isSet(object.quantity_delta)
        ? globalThis.Number(object.quantity_delta)
        : 0,
      reason: isSet(object.reason) ? inventoryChangeReasonFromJSON(object.reason) : 0,
    };
  },

  toJSON(message: InventoryDiff): unknown {
    const obj: any = {};
    if (message.itemId !== undefined && message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      obj.itemState = Math.round(message.itemState);
    }
    if (message.quantityDelta !== undefined && message.quantityDelta !== 0) {
      obj.quantityDelta = message.quantityDelta;
    }
    if (message.reason !== undefined && message.reason !== 0) {
      obj.reason = inventoryChangeReasonToJSON(message.reason);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InventoryDiff>, I>>(base?: I): InventoryDiff {
    return InventoryDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InventoryDiff>, I>>(object: I): InventoryDiff {
    const message = createBaseInventoryDiff();
    message.itemId = object.itemId ?? 0;
    message.itemState = object.itemState ?? 0;
    message.quantityDelta = object.quantityDelta ?? 0;
    message.reason = object.reason ?? 0;
    return message;
  },
};

function createBaseInventoryFull(): InventoryFull {
  return { itemId: 0, itemState: 0, quantity: 0 };
}

export const InventoryFull: MessageFns<InventoryFull> = {
  encode(message: InventoryFull, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== undefined && message.itemId !== 0) {
      writer.uint32(8).int32(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      writer.uint32(16).int32(message.itemState);
    }
    if (message.quantity !== undefined && message.quantity !== 0) {
      writer.uint32(25).double(message.quantity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InventoryFull {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInventoryFull();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.itemId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemState = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InventoryFull {
    return {
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
        ? globalThis.Number(object.item_id)
        : 0,
      itemState: isSet(object.itemState)
        ? globalThis.Number(object.itemState)
        : isSet(object.item_state)
        ? globalThis.Number(object.item_state)
        : 0,
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: InventoryFull): unknown {
    const obj: any = {};
    if (message.itemId !== undefined && message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      obj.itemState = Math.round(message.itemState);
    }
    if (message.quantity !== undefined && message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InventoryFull>, I>>(base?: I): InventoryFull {
    return InventoryFull.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InventoryFull>, I>>(object: I): InventoryFull {
    const message = createBaseInventoryFull();
    message.itemId = object.itemId ?? 0;
    message.itemState = object.itemState ?? 0;
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseModifierWire(): ModifierWire {
  return { source: "", op: "", value: 0, refAttr: "", display: "" };
}

export const ModifierWire: MessageFns<ModifierWire> = {
  encode(message: ModifierWire, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== undefined && message.source !== "") {
      writer.uint32(10).string(message.source);
    }
    if (message.op !== undefined && message.op !== "") {
      writer.uint32(18).string(message.op);
    }
    if (message.value !== undefined && message.value !== 0) {
      writer.uint32(25).double(message.value);
    }
    if (message.refAttr !== undefined && message.refAttr !== "") {
      writer.uint32(34).string(message.refAttr);
    }
    if (message.display !== undefined && message.display !== "") {
      writer.uint32(42).string(message.display);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModifierWire {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModifierWire();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.op = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.value = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.refAttr = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.display = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModifierWire {
    return {
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      op: isSet(object.op) ? globalThis.String(object.op) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      refAttr: isSet(object.refAttr)
        ? globalThis.String(object.refAttr)
        : isSet(object.ref_attr)
        ? globalThis.String(object.ref_attr)
        : "",
      display: isSet(object.display) ? globalThis.String(object.display) : "",
    };
  },

  toJSON(message: ModifierWire): unknown {
    const obj: any = {};
    if (message.source !== undefined && message.source !== "") {
      obj.source = message.source;
    }
    if (message.op !== undefined && message.op !== "") {
      obj.op = message.op;
    }
    if (message.value !== undefined && message.value !== 0) {
      obj.value = message.value;
    }
    if (message.refAttr !== undefined && message.refAttr !== "") {
      obj.refAttr = message.refAttr;
    }
    if (message.display !== undefined && message.display !== "") {
      obj.display = message.display;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModifierWire>, I>>(base?: I): ModifierWire {
    return ModifierWire.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModifierWire>, I>>(object: I): ModifierWire {
    const message = createBaseModifierWire();
    message.source = object.source ?? "";
    message.op = object.op ?? "";
    message.value = object.value ?? 0;
    message.refAttr = object.refAttr ?? "";
    message.display = object.display ?? "";
    return message;
  },
};

function createBaseAttributeDiff(): AttributeDiff {
  return { attrId: "", finalValue: 0, modifiers: [] };
}

export const AttributeDiff: MessageFns<AttributeDiff> = {
  encode(message: AttributeDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attrId !== undefined && message.attrId !== "") {
      writer.uint32(10).string(message.attrId);
    }
    if (message.finalValue !== undefined && message.finalValue !== 0) {
      writer.uint32(17).double(message.finalValue);
    }
    if (message.modifiers !== undefined && message.modifiers.length !== 0) {
      for (const v of message.modifiers) {
        ModifierWire.encode(v!, writer.uint32(26).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttributeDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttributeDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attrId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.finalValue = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = ModifierWire.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.modifiers!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttributeDiff {
    return {
      attrId: isSet(object.attrId)
        ? globalThis.String(object.attrId)
        : isSet(object.attr_id)
        ? globalThis.String(object.attr_id)
        : "",
      finalValue: isSet(object.finalValue)
        ? globalThis.Number(object.finalValue)
        : isSet(object.final_value)
        ? globalThis.Number(object.final_value)
        : 0,
      modifiers: globalThis.Array.isArray(object?.modifiers)
        ? object.modifiers.map((e: any) => ModifierWire.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AttributeDiff): unknown {
    const obj: any = {};
    if (message.attrId !== undefined && message.attrId !== "") {
      obj.attrId = message.attrId;
    }
    if (message.finalValue !== undefined && message.finalValue !== 0) {
      obj.finalValue = message.finalValue;
    }
    if (message.modifiers?.length) {
      obj.modifiers = message.modifiers.map((e) => ModifierWire.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttributeDiff>, I>>(base?: I): AttributeDiff {
    return AttributeDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttributeDiff>, I>>(object: I): AttributeDiff {
    const message = createBaseAttributeDiff();
    message.attrId = object.attrId ?? "";
    message.finalValue = object.finalValue ?? 0;
    message.modifiers = object.modifiers?.map((e) => ModifierWire.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAttributeFull(): AttributeFull {
  return { attrId: "", name: "", finalValue: 0, group: "", direction: "", modifiers: [] };
}

export const AttributeFull: MessageFns<AttributeFull> = {
  encode(message: AttributeFull, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attrId !== undefined && message.attrId !== "") {
      writer.uint32(10).string(message.attrId);
    }
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.finalValue !== undefined && message.finalValue !== 0) {
      writer.uint32(25).double(message.finalValue);
    }
    if (message.group !== undefined && message.group !== "") {
      writer.uint32(34).string(message.group);
    }
    if (message.direction !== undefined && message.direction !== "") {
      writer.uint32(42).string(message.direction);
    }
    if (message.modifiers !== undefined && message.modifiers.length !== 0) {
      for (const v of message.modifiers) {
        ModifierWire.encode(v!, writer.uint32(50).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttributeFull {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttributeFull();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attrId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.finalValue = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.group = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.direction = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const el = ModifierWire.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.modifiers!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttributeFull {
    return {
      attrId: isSet(object.attrId)
        ? globalThis.String(object.attrId)
        : isSet(object.attr_id)
        ? globalThis.String(object.attr_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      finalValue: isSet(object.finalValue)
        ? globalThis.Number(object.finalValue)
        : isSet(object.final_value)
        ? globalThis.Number(object.final_value)
        : 0,
      group: isSet(object.group) ? globalThis.String(object.group) : "",
      direction: isSet(object.direction) ? globalThis.String(object.direction) : "",
      modifiers: globalThis.Array.isArray(object?.modifiers)
        ? object.modifiers.map((e: any) => ModifierWire.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AttributeFull): unknown {
    const obj: any = {};
    if (message.attrId !== undefined && message.attrId !== "") {
      obj.attrId = message.attrId;
    }
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    if (message.finalValue !== undefined && message.finalValue !== 0) {
      obj.finalValue = message.finalValue;
    }
    if (message.group !== undefined && message.group !== "") {
      obj.group = message.group;
    }
    if (message.direction !== undefined && message.direction !== "") {
      obj.direction = message.direction;
    }
    if (message.modifiers?.length) {
      obj.modifiers = message.modifiers.map((e) => ModifierWire.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttributeFull>, I>>(base?: I): AttributeFull {
    return AttributeFull.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttributeFull>, I>>(object: I): AttributeFull {
    const message = createBaseAttributeFull();
    message.attrId = object.attrId ?? "";
    message.name = object.name ?? "";
    message.finalValue = object.finalValue ?? 0;
    message.group = object.group ?? "";
    message.direction = object.direction ?? "";
    message.modifiers = object.modifiers?.map((e) => ModifierWire.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSkillXPDiff(): SkillXPDiff {
  return { skillId: 0, xpDelta: 0, newLevel: 0 };
}

export const SkillXPDiff: MessageFns<SkillXPDiff> = {
  encode(message: SkillXPDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.skillId !== undefined && message.skillId !== 0) {
      writer.uint32(8).int64(message.skillId);
    }
    if (message.xpDelta !== undefined && message.xpDelta !== 0) {
      writer.uint32(17).double(message.xpDelta);
    }
    if (message.newLevel !== undefined && message.newLevel !== 0) {
      writer.uint32(25).double(message.newLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SkillXPDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSkillXPDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.skillId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.xpDelta = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.newLevel = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SkillXPDiff {
    return {
      skillId: isSet(object.skillId)
        ? globalThis.Number(object.skillId)
        : isSet(object.skill_id)
        ? globalThis.Number(object.skill_id)
        : 0,
      xpDelta: isSet(object.xpDelta)
        ? globalThis.Number(object.xpDelta)
        : isSet(object.xp_delta)
        ? globalThis.Number(object.xp_delta)
        : 0,
      newLevel: isSet(object.newLevel)
        ? globalThis.Number(object.newLevel)
        : isSet(object.new_level)
        ? globalThis.Number(object.new_level)
        : 0,
    };
  },

  toJSON(message: SkillXPDiff): unknown {
    const obj: any = {};
    if (message.skillId !== undefined && message.skillId !== 0) {
      obj.skillId = Math.round(message.skillId);
    }
    if (message.xpDelta !== undefined && message.xpDelta !== 0) {
      obj.xpDelta = message.xpDelta;
    }
    if (message.newLevel !== undefined && message.newLevel !== 0) {
      obj.newLevel = message.newLevel;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SkillXPDiff>, I>>(base?: I): SkillXPDiff {
    return SkillXPDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SkillXPDiff>, I>>(object: I): SkillXPDiff {
    const message = createBaseSkillXPDiff();
    message.skillId = object.skillId ?? 0;
    message.xpDelta = object.xpDelta ?? 0;
    message.newLevel = object.newLevel ?? 0;
    return message;
  },
};

function createBaseSkillXPFull(): SkillXPFull {
  return { skillId: 0, level: 0, xp: 0 };
}

export const SkillXPFull: MessageFns<SkillXPFull> = {
  encode(message: SkillXPFull, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.skillId !== undefined && message.skillId !== 0) {
      writer.uint32(8).int64(message.skillId);
    }
    if (message.level !== undefined && message.level !== 0) {
      writer.uint32(17).double(message.level);
    }
    if (message.xp !== undefined && message.xp !== 0) {
      writer.uint32(25).double(message.xp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SkillXPFull {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSkillXPFull();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.skillId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.level = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.xp = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SkillXPFull {
    return {
      skillId: isSet(object.skillId)
        ? globalThis.Number(object.skillId)
        : isSet(object.skill_id)
        ? globalThis.Number(object.skill_id)
        : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      xp: isSet(object.xp) ? globalThis.Number(object.xp) : 0,
    };
  },

  toJSON(message: SkillXPFull): unknown {
    const obj: any = {};
    if (message.skillId !== undefined && message.skillId !== 0) {
      obj.skillId = Math.round(message.skillId);
    }
    if (message.level !== undefined && message.level !== 0) {
      obj.level = message.level;
    }
    if (message.xp !== undefined && message.xp !== 0) {
      obj.xp = message.xp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SkillXPFull>, I>>(base?: I): SkillXPFull {
    return SkillXPFull.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SkillXPFull>, I>>(object: I): SkillXPFull {
    const message = createBaseSkillXPFull();
    message.skillId = object.skillId ?? 0;
    message.level = object.level ?? 0;
    message.xp = object.xp ?? 0;
    return message;
  },
};

function createBaseBestiaryDiff(): BestiaryDiff {
  return { type: "", id: "" };
}

export const BestiaryDiff: MessageFns<BestiaryDiff> = {
  encode(message: BestiaryDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== undefined && message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BestiaryDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBestiaryDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BestiaryDiff {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: BestiaryDiff): unknown {
    const obj: any = {};
    if (message.type !== undefined && message.type !== "") {
      obj.type = message.type;
    }
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BestiaryDiff>, I>>(base?: I): BestiaryDiff {
    return BestiaryDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BestiaryDiff>, I>>(object: I): BestiaryDiff {
    const message = createBaseBestiaryDiff();
    message.type = object.type ?? "";
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseBestiaryFull(): BestiaryFull {
  return { type: "", id: "" };
}

export const BestiaryFull: MessageFns<BestiaryFull> = {
  encode(message: BestiaryFull, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== undefined && message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BestiaryFull {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBestiaryFull();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BestiaryFull {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: BestiaryFull): unknown {
    const obj: any = {};
    if (message.type !== undefined && message.type !== "") {
      obj.type = message.type;
    }
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BestiaryFull>, I>>(base?: I): BestiaryFull {
    return BestiaryFull.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BestiaryFull>, I>>(object: I): BestiaryFull {
    const message = createBaseBestiaryFull();
    message.type = object.type ?? "";
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseEventExecutionDiff(): EventExecutionDiff {
  return { eventId: 0, cycles: 0 };
}

export const EventExecutionDiff: MessageFns<EventExecutionDiff> = {
  encode(message: EventExecutionDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== undefined && message.eventId !== 0) {
      writer.uint32(8).int64(message.eventId);
    }
    if (message.cycles !== undefined && message.cycles !== 0) {
      writer.uint32(16).int32(message.cycles);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventExecutionDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventExecutionDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cycles = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventExecutionDiff {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      cycles: isSet(object.cycles) ? globalThis.Number(object.cycles) : 0,
    };
  },

  toJSON(message: EventExecutionDiff): unknown {
    const obj: any = {};
    if (message.eventId !== undefined && message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.cycles !== undefined && message.cycles !== 0) {
      obj.cycles = Math.round(message.cycles);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventExecutionDiff>, I>>(base?: I): EventExecutionDiff {
    return EventExecutionDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventExecutionDiff>, I>>(object: I): EventExecutionDiff {
    const message = createBaseEventExecutionDiff();
    message.eventId = object.eventId ?? 0;
    message.cycles = object.cycles ?? 0;
    return message;
  },
};

function createBaseEventExecutionFull(): EventExecutionFull {
  return { queueId: 0, eventId: 0, targetCycles: 0, progress: 0 };
}

export const EventExecutionFull: MessageFns<EventExecutionFull> = {
  encode(message: EventExecutionFull, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueId !== undefined && message.queueId !== 0) {
      writer.uint32(8).int32(message.queueId);
    }
    if (message.eventId !== undefined && message.eventId !== 0) {
      writer.uint32(16).int64(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      writer.uint32(24).int32(message.targetCycles);
    }
    if (message.progress !== undefined && message.progress !== 0) {
      writer.uint32(33).double(message.progress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventExecutionFull {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventExecutionFull();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.queueId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.eventId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.targetCycles = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.progress = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventExecutionFull {
    return {
      queueId: isSet(object.queueId)
        ? globalThis.Number(object.queueId)
        : isSet(object.queue_id)
        ? globalThis.Number(object.queue_id)
        : 0,
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      targetCycles: isSet(object.targetCycles)
        ? globalThis.Number(object.targetCycles)
        : isSet(object.target_cycles)
        ? globalThis.Number(object.target_cycles)
        : 0,
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
    };
  },

  toJSON(message: EventExecutionFull): unknown {
    const obj: any = {};
    if (message.queueId !== undefined && message.queueId !== 0) {
      obj.queueId = Math.round(message.queueId);
    }
    if (message.eventId !== undefined && message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      obj.targetCycles = Math.round(message.targetCycles);
    }
    if (message.progress !== undefined && message.progress !== 0) {
      obj.progress = message.progress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventExecutionFull>, I>>(base?: I): EventExecutionFull {
    return EventExecutionFull.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventExecutionFull>, I>>(object: I): EventExecutionFull {
    const message = createBaseEventExecutionFull();
    message.queueId = object.queueId ?? 0;
    message.eventId = object.eventId ?? 0;
    message.targetCycles = object.targetCycles ?? 0;
    message.progress = object.progress ?? 0;
    return message;
  },
};

function createBaseEventQueueEntry(): EventQueueEntry {
  return { position: 0, eventId: 0, targetCycles: 0, progress: 0 };
}

export const EventQueueEntry: MessageFns<EventQueueEntry> = {
  encode(message: EventQueueEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== undefined && message.position !== 0) {
      writer.uint32(8).int32(message.position);
    }
    if (message.eventId !== undefined && message.eventId !== 0) {
      writer.uint32(16).int64(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      writer.uint32(24).int32(message.targetCycles);
    }
    if (message.progress !== undefined && message.progress !== 0) {
      writer.uint32(33).double(message.progress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventQueueEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventQueueEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.position = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.eventId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.targetCycles = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.progress = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventQueueEntry {
    return {
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      targetCycles: isSet(object.targetCycles)
        ? globalThis.Number(object.targetCycles)
        : isSet(object.target_cycles)
        ? globalThis.Number(object.target_cycles)
        : 0,
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
    };
  },

  toJSON(message: EventQueueEntry): unknown {
    const obj: any = {};
    if (message.position !== undefined && message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    if (message.eventId !== undefined && message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.targetCycles !== undefined && message.targetCycles !== 0) {
      obj.targetCycles = Math.round(message.targetCycles);
    }
    if (message.progress !== undefined && message.progress !== 0) {
      obj.progress = message.progress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventQueueEntry>, I>>(base?: I): EventQueueEntry {
    return EventQueueEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventQueueEntry>, I>>(object: I): EventQueueEntry {
    const message = createBaseEventQueueEntry();
    message.position = object.position ?? 0;
    message.eventId = object.eventId ?? 0;
    message.targetCycles = object.targetCycles ?? 0;
    message.progress = object.progress ?? 0;
    return message;
  },
};

function createBaseEventQueueDiff(): EventQueueDiff {
  return { queueId: 0, scope: "", entries: [] };
}

export const EventQueueDiff: MessageFns<EventQueueDiff> = {
  encode(message: EventQueueDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueId !== undefined && message.queueId !== 0) {
      writer.uint32(8).int32(message.queueId);
    }
    if (message.scope !== undefined && message.scope !== "") {
      writer.uint32(18).string(message.scope);
    }
    if (message.entries !== undefined && message.entries.length !== 0) {
      for (const v of message.entries) {
        EventQueueEntry.encode(v!, writer.uint32(26).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventQueueDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventQueueDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.queueId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = EventQueueEntry.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.entries!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventQueueDiff {
    return {
      queueId: isSet(object.queueId)
        ? globalThis.Number(object.queueId)
        : isSet(object.queue_id)
        ? globalThis.Number(object.queue_id)
        : 0,
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => EventQueueEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EventQueueDiff): unknown {
    const obj: any = {};
    if (message.queueId !== undefined && message.queueId !== 0) {
      obj.queueId = Math.round(message.queueId);
    }
    if (message.scope !== undefined && message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => EventQueueEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventQueueDiff>, I>>(base?: I): EventQueueDiff {
    return EventQueueDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventQueueDiff>, I>>(object: I): EventQueueDiff {
    const message = createBaseEventQueueDiff();
    message.queueId = object.queueId ?? 0;
    message.scope = object.scope ?? "";
    message.entries = object.entries?.map((e) => EventQueueEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEquipmentDiff(): EquipmentDiff {
  return { slot: "", itemId: 0, itemState: 0, action: 0 };
}

export const EquipmentDiff: MessageFns<EquipmentDiff> = {
  encode(message: EquipmentDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slot !== undefined && message.slot !== "") {
      writer.uint32(10).string(message.slot);
    }
    if (message.itemId !== undefined && message.itemId !== 0) {
      writer.uint32(16).int32(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      writer.uint32(24).int32(message.itemState);
    }
    if (message.action !== undefined && message.action !== 0) {
      writer.uint32(32).int32(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EquipmentDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEquipmentDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slot = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.itemState = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.action = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EquipmentDiff {
    return {
      slot: isSet(object.slot) ? globalThis.String(object.slot) : "",
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
        ? globalThis.Number(object.item_id)
        : 0,
      itemState: isSet(object.itemState)
        ? globalThis.Number(object.itemState)
        : isSet(object.item_state)
        ? globalThis.Number(object.item_state)
        : 0,
      action: isSet(object.action) ? equipActionFromJSON(object.action) : 0,
    };
  },

  toJSON(message: EquipmentDiff): unknown {
    const obj: any = {};
    if (message.slot !== undefined && message.slot !== "") {
      obj.slot = message.slot;
    }
    if (message.itemId !== undefined && message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.itemState !== undefined && message.itemState !== 0) {
      obj.itemState = Math.round(message.itemState);
    }
    if (message.action !== undefined && message.action !== 0) {
      obj.action = equipActionToJSON(message.action);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EquipmentDiff>, I>>(base?: I): EquipmentDiff {
    return EquipmentDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EquipmentDiff>, I>>(object: I): EquipmentDiff {
    const message = createBaseEquipmentDiff();
    message.slot = object.slot ?? "";
    message.itemId = object.itemId ?? 0;
    message.itemState = object.itemState ?? 0;
    message.action = object.action ?? 0;
    return message;
  },
};

function createBaseStateDiff(): StateDiff {
  return { inventory: [], attribute: [], skillXp: [], bestiary: [], eventExecution: [], eventQueue: [], equipment: [] };
}

export const StateDiff: MessageFns<StateDiff> = {
  encode(message: StateDiff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.inventory !== undefined && message.inventory.length !== 0) {
      for (const v of message.inventory) {
        InventoryDiff.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    if (message.attribute !== undefined && message.attribute.length !== 0) {
      for (const v of message.attribute) {
        AttributeDiff.encode(v!, writer.uint32(18).fork()).join();
      }
    }
    if (message.skillXp !== undefined && message.skillXp.length !== 0) {
      for (const v of message.skillXp) {
        SkillXPDiff.encode(v!, writer.uint32(26).fork()).join();
      }
    }
    if (message.bestiary !== undefined && message.bestiary.length !== 0) {
      for (const v of message.bestiary) {
        BestiaryDiff.encode(v!, writer.uint32(34).fork()).join();
      }
    }
    if (message.eventExecution !== undefined && message.eventExecution.length !== 0) {
      for (const v of message.eventExecution) {
        EventExecutionDiff.encode(v!, writer.uint32(42).fork()).join();
      }
    }
    if (message.eventQueue !== undefined && message.eventQueue.length !== 0) {
      for (const v of message.eventQueue) {
        EventQueueDiff.encode(v!, writer.uint32(50).fork()).join();
      }
    }
    if (message.equipment !== undefined && message.equipment.length !== 0) {
      for (const v of message.equipment) {
        EquipmentDiff.encode(v!, writer.uint32(58).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateDiff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateDiff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = InventoryDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.inventory!.push(el);
          }
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const el = AttributeDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.attribute!.push(el);
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = SkillXPDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.skillXp!.push(el);
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const el = BestiaryDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.bestiary!.push(el);
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const el = EventExecutionDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.eventExecution!.push(el);
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const el = EventQueueDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.eventQueue!.push(el);
          }
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const el = EquipmentDiff.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.equipment!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateDiff {
    return {
      inventory: globalThis.Array.isArray(object?.inventory)
        ? object.inventory.map((e: any) => InventoryDiff.fromJSON(e))
        : [],
      attribute: globalThis.Array.isArray(object?.attribute)
        ? object.attribute.map((e: any) => AttributeDiff.fromJSON(e))
        : [],
      skillXp: globalThis.Array.isArray(object?.skillXp)
        ? object.skillXp.map((e: any) => SkillXPDiff.fromJSON(e))
        : globalThis.Array.isArray(object?.skill_xp)
        ? object.skill_xp.map((e: any) => SkillXPDiff.fromJSON(e))
        : [],
      bestiary: globalThis.Array.isArray(object?.bestiary)
        ? object.bestiary.map((e: any) => BestiaryDiff.fromJSON(e))
        : [],
      eventExecution: globalThis.Array.isArray(object?.eventExecution)
        ? object.eventExecution.map((e: any) => EventExecutionDiff.fromJSON(e))
        : globalThis.Array.isArray(object?.event_execution)
        ? object.event_execution.map((e: any) => EventExecutionDiff.fromJSON(e))
        : [],
      eventQueue: globalThis.Array.isArray(object?.eventQueue)
        ? object.eventQueue.map((e: any) => EventQueueDiff.fromJSON(e))
        : globalThis.Array.isArray(object?.event_queue)
        ? object.event_queue.map((e: any) => EventQueueDiff.fromJSON(e))
        : [],
      equipment: globalThis.Array.isArray(object?.equipment)
        ? object.equipment.map((e: any) => EquipmentDiff.fromJSON(e))
        : [],
    };
  },

  toJSON(message: StateDiff): unknown {
    const obj: any = {};
    if (message.inventory?.length) {
      obj.inventory = message.inventory.map((e) => InventoryDiff.toJSON(e));
    }
    if (message.attribute?.length) {
      obj.attribute = message.attribute.map((e) => AttributeDiff.toJSON(e));
    }
    if (message.skillXp?.length) {
      obj.skillXp = message.skillXp.map((e) => SkillXPDiff.toJSON(e));
    }
    if (message.bestiary?.length) {
      obj.bestiary = message.bestiary.map((e) => BestiaryDiff.toJSON(e));
    }
    if (message.eventExecution?.length) {
      obj.eventExecution = message.eventExecution.map((e) => EventExecutionDiff.toJSON(e));
    }
    if (message.eventQueue?.length) {
      obj.eventQueue = message.eventQueue.map((e) => EventQueueDiff.toJSON(e));
    }
    if (message.equipment?.length) {
      obj.equipment = message.equipment.map((e) => EquipmentDiff.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateDiff>, I>>(base?: I): StateDiff {
    return StateDiff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateDiff>, I>>(object: I): StateDiff {
    const message = createBaseStateDiff();
    message.inventory = object.inventory?.map((e) => InventoryDiff.fromPartial(e)) || [];
    message.attribute = object.attribute?.map((e) => AttributeDiff.fromPartial(e)) || [];
    message.skillXp = object.skillXp?.map((e) => SkillXPDiff.fromPartial(e)) || [];
    message.bestiary = object.bestiary?.map((e) => BestiaryDiff.fromPartial(e)) || [];
    message.eventExecution = object.eventExecution?.map((e) => EventExecutionDiff.fromPartial(e)) || [];
    message.eventQueue = object.eventQueue?.map((e) => EventQueueDiff.fromPartial(e)) || [];
    message.equipment = object.equipment?.map((e) => EquipmentDiff.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStateFull(): StateFull {
  return { inventory: [], attribute: [], skillXp: [], bestiary: [], eventExecution: [], equipment: {} };
}

export const StateFull: MessageFns<StateFull> = {
  encode(message: StateFull, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.inventory !== undefined && message.inventory.length !== 0) {
      for (const v of message.inventory) {
        InventoryFull.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    if (message.attribute !== undefined && message.attribute.length !== 0) {
      for (const v of message.attribute) {
        AttributeFull.encode(v!, writer.uint32(18).fork()).join();
      }
    }
    if (message.skillXp !== undefined && message.skillXp.length !== 0) {
      for (const v of message.skillXp) {
        SkillXPFull.encode(v!, writer.uint32(26).fork()).join();
      }
    }
    if (message.bestiary !== undefined && message.bestiary.length !== 0) {
      for (const v of message.bestiary) {
        BestiaryFull.encode(v!, writer.uint32(34).fork()).join();
      }
    }
    if (message.eventExecution !== undefined && message.eventExecution.length !== 0) {
      for (const v of message.eventExecution) {
        EventExecutionFull.encode(v!, writer.uint32(42).fork()).join();
      }
    }
    globalThis.Object.entries(message.equipment || {}).forEach(([key, value]: [string, ItemIdentity]) => {
      StateFull_EquipmentEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateFull {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateFull();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = InventoryFull.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.inventory!.push(el);
          }
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const el = AttributeFull.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.attribute!.push(el);
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = SkillXPFull.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.skillXp!.push(el);
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const el = BestiaryFull.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.bestiary!.push(el);
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const el = EventExecutionFull.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.eventExecution!.push(el);
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = StateFull_EquipmentEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.equipment![entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateFull {
    return {
      inventory: globalThis.Array.isArray(object?.inventory)
        ? object.inventory.map((e: any) => InventoryFull.fromJSON(e))
        : [],
      attribute: globalThis.Array.isArray(object?.attribute)
        ? object.attribute.map((e: any) => AttributeFull.fromJSON(e))
        : [],
      skillXp: globalThis.Array.isArray(object?.skillXp)
        ? object.skillXp.map((e: any) => SkillXPFull.fromJSON(e))
        : globalThis.Array.isArray(object?.skill_xp)
        ? object.skill_xp.map((e: any) => SkillXPFull.fromJSON(e))
        : [],
      bestiary: globalThis.Array.isArray(object?.bestiary)
        ? object.bestiary.map((e: any) => BestiaryFull.fromJSON(e))
        : [],
      eventExecution: globalThis.Array.isArray(object?.eventExecution)
        ? object.eventExecution.map((e: any) => EventExecutionFull.fromJSON(e))
        : globalThis.Array.isArray(object?.event_execution)
        ? object.event_execution.map((e: any) => EventExecutionFull.fromJSON(e))
        : [],
      equipment: isObject(object.equipment)
        ? (globalThis.Object.entries(object.equipment) as [string, any][]).reduce(
          (acc: { [key: string]: ItemIdentity }, [key, value]: [string, any]) => {
            acc[key] = ItemIdentity.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: StateFull): unknown {
    const obj: any = {};
    if (message.inventory?.length) {
      obj.inventory = message.inventory.map((e) => InventoryFull.toJSON(e));
    }
    if (message.attribute?.length) {
      obj.attribute = message.attribute.map((e) => AttributeFull.toJSON(e));
    }
    if (message.skillXp?.length) {
      obj.skillXp = message.skillXp.map((e) => SkillXPFull.toJSON(e));
    }
    if (message.bestiary?.length) {
      obj.bestiary = message.bestiary.map((e) => BestiaryFull.toJSON(e));
    }
    if (message.eventExecution?.length) {
      obj.eventExecution = message.eventExecution.map((e) => EventExecutionFull.toJSON(e));
    }
    if (message.equipment) {
      const entries = globalThis.Object.entries(message.equipment) as [string, ItemIdentity][];
      if (entries.length > 0) {
        obj.equipment = {};
        entries.forEach(([k, v]) => {
          obj.equipment[k] = ItemIdentity.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateFull>, I>>(base?: I): StateFull {
    return StateFull.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateFull>, I>>(object: I): StateFull {
    const message = createBaseStateFull();
    message.inventory = object.inventory?.map((e) => InventoryFull.fromPartial(e)) || [];
    message.attribute = object.attribute?.map((e) => AttributeFull.fromPartial(e)) || [];
    message.skillXp = object.skillXp?.map((e) => SkillXPFull.fromPartial(e)) || [];
    message.bestiary = object.bestiary?.map((e) => BestiaryFull.fromPartial(e)) || [];
    message.eventExecution = object.eventExecution?.map((e) => EventExecutionFull.fromPartial(e)) || [];
    message.equipment = (globalThis.Object.entries(object.equipment ?? {}) as [string, ItemIdentity][]).reduce(
      (acc: { [key: string]: ItemIdentity }, [key, value]: [string, ItemIdentity]) => {
        if (value !== undefined) {
          acc[key] = ItemIdentity.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseStateFull_EquipmentEntry(): StateFull_EquipmentEntry {
  return { key: "", value: undefined };
}

export const StateFull_EquipmentEntry: MessageFns<StateFull_EquipmentEntry> = {
  encode(message: StateFull_EquipmentEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      ItemIdentity.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateFull_EquipmentEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateFull_EquipmentEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ItemIdentity.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateFull_EquipmentEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? ItemIdentity.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: StateFull_EquipmentEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ItemIdentity.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateFull_EquipmentEntry>, I>>(base?: I): StateFull_EquipmentEntry {
    return StateFull_EquipmentEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateFull_EquipmentEntry>, I>>(object: I): StateFull_EquipmentEntry {
    const message = createBaseStateFull_EquipmentEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ItemIdentity.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
